"""boshlangich sxema (mavjud modellarga mos baseline)

Revision ID: e746589ef33a
Revises:
Create Date: 2026-09-14 06:13:02.612060

MUHIM (2026-09, Item J auditi, 🟡 O'RTA, 19-band -- "migratsiya tizimi
yo'q" muammosiga javoban qo'shildi): bu -- BIRINCHI Alembic revizyasi.
U `db.py`dagi HOZIRGI modellarga (bo'sh bazadan) mos keladigan "create
all" ko'rinishidagi to'liq sxemani ifodalaydi -- `sqlite:///` bo'sh
bazada avtogenerate orqali yaratilgan va tekshirilgan (upgrade/downgrade
ikkalasi ham xatosiz o'tdi, qayta avtogenerate 0 farq ko'rsatdi).

PRODUCTION (Render, mavjud Postgres) uchun MUHIM: bu bazada jadvallar
ALLAQACHON mavjud -- ular yillar davomida `db._migrate_add_missing_
columns()` (o'z-o'zini ALTER TABLE qiluvchi, Alembic'siz mexanizm,
hali ham `init_db()`da ishlaydi va olib tashlanmagan) orqali qurilgan.
Shu sababli production bazada bu revizyani ODATDAGIDEK
`alembic upgrade head` bilan EMAS, balki:

    alembic stamp head

bilan "faqat belgilash" (mavjud sxemani o'zgartirmasdan, faqat Alembic
o'ziga "biz allaqachon shu revizyadamiz" deb yozib qo'yish) kerak bo'ladi
-- BIR MARTA, birinchi joriy etishda. `alembic upgrade head`ni haqiqiy
production'ga sinovsiz qo'llash BU SANDBOX'DAN tasdiqlanmagan (bu yerda
tarmoq orqali production Postgres'ga ulanish yo'q) -- shu sababli avtomatik
ishga tushirish (masalan `render.yaml`ga qo'shish) ATAYLAB QILINMADI;
foydalanuvchi buni qachon va qanday joriy etishni o'zi hal qiladi.
Shundan KEYIN yozilgan barcha yangi revizyalar odatdagidek
`alembic upgrade head` bilan qo'llanishi mumkin.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e746589ef33a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=True),
    sa.Column('meta_access_token', sa.Text(), nullable=True),
    sa.Column('meta_ad_account_id', sa.String(length=32), nullable=True),
    sa.Column('meta_page_id', sa.String(length=32), nullable=True),
    sa.Column('ig_business_id', sa.String(length=32), nullable=True),
    sa.Column('ig_dm_sync_since', sa.DateTime(), nullable=True),
    sa.Column('meta_pixel_id', sa.String(length=32), nullable=True),
    sa.Column('telegram_group_id', sa.String(length=32), nullable=True),
    sa.Column('meta_business_id', sa.String(length=32), nullable=True),
    sa.Column('meta_business_name', sa.String(length=255), nullable=True),
    sa.Column('meta_ad_account_name', sa.String(length=255), nullable=True),
    sa.Column('meta_dataset_name', sa.String(length=255), nullable=True),
    sa.Column('meta_token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('meta_integration_status', sa.String(length=20), nullable=False),
    sa.Column('meta_last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('meta_last_event_at', sa.DateTime(), nullable=True),
    sa.Column('meta_capi_dataset_id', sa.String(length=32), nullable=True),
    sa.Column('meta_capi_access_token', sa.Text(), nullable=True),
    sa.Column('disabled_modules', sa.Text(), nullable=True),
    sa.Column('ai_features_disabled', sa.Boolean(), nullable=False),
    sa.Column('auto_watch_enabled', sa.Boolean(), nullable=True),
    sa.Column('webhook_out_url', sa.String(length=500), nullable=True),
    sa.Column('webhook_out_secret', sa.String(length=128), nullable=True),
    sa.Column('webhook_out_last_status', sa.String(length=16), nullable=True),
    sa.Column('webhook_out_last_at', sa.DateTime(), nullable=True),
    sa.Column('webhook_out_last_error', sa.Text(), nullable=True),
    sa.Column('webhook_out_crm_name', sa.String(length=64), nullable=True),
    sa.Column('inbound_lead_token', sa.String(length=64), nullable=True),
    sa.Column('inbound_lead_last_at', sa.DateTime(), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('paid_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('payme_card_token', sa.Text(), nullable=True),
    sa.Column('payme_card_masked', sa.String(length=32), nullable=True),
    sa.Column('payme_card_pending_token', sa.Text(), nullable=True),
    sa.Column('payme_autopay_enabled', sa.Boolean(), nullable=False),
    sa.Column('moizvonki_api_address', sa.String(length=255), nullable=True),
    sa.Column('moizvonki_user_name', sa.String(length=255), nullable=True),
    sa.Column('moizvonki_api_key', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_companies_inbound_lead_token'), 'companies', ['inbound_lead_token'], unique=True)
    op.create_table('kv_store',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('canned_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canned_replies_company_id'), 'canned_replies', ['company_id'], unique=False)
    op.create_table('competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('search_term', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitors_company_id'), 'competitors', ['company_id'], unique=False)
    op.create_table('custom_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('field_type', sa.String(length=16), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'key', name='uq_custom_fields_company_key')
    )
    op.create_index(op.f('ix_custom_fields_company_id'), 'custom_fields', ['company_id'], unique=False)
    op.create_table('funnel_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'key', name='uq_funnel_stages_company_key')
    )
    op.create_index(op.f('ix_funnel_stages_company_id'), 'funnel_stages', ['company_id'], unique=False)
    op.create_table('ig_dm_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('customer_ig_id', sa.String(length=64), nullable=True),
    sa.Column('customer_username', sa.String(length=255), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('last_message_text', sa.Text(), nullable=True),
    sa.Column('last_message_from', sa.String(length=16), nullable=True),
    sa.Column('is_unanswered', sa.Boolean(), nullable=False),
    sa.Column('unanswered_since', sa.DateTime(), nullable=True),
    sa.Column('unanswered_alert_sent_at', sa.DateTime(), nullable=True),
    sa.Column('ai_lead_quality', sa.String(length=16), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_reasons', sa.Text(), nullable=True),
    sa.Column('ai_analyzed_message_count', sa.Integer(), nullable=False),
    sa.Column('ai_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('ai_model', sa.String(length=64), nullable=True),
    sa.Column('ai_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_ig_dm_conversations_company_id'), 'ig_dm_conversations', ['company_id'], unique=False)
    op.create_index(op.f('ix_ig_dm_conversations_customer_ig_id'), 'ig_dm_conversations', ['customer_ig_id'], unique=False)
    op.create_index(op.f('ix_ig_dm_conversations_last_message_at'), 'ig_dm_conversations', ['last_message_at'], unique=False)
    op.create_table('managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=32), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('moizvonki_login', sa.String(length=128), nullable=True),
    sa.Column('allowed_modules', sa.Text(), nullable=True),
    sa.Column('hire_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_managers_company_id'), 'managers', ['company_id'], unique=False)
    op.create_table('payme_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('payme_receipt_id', sa.String(length=64), nullable=True),
    sa.Column('plan_key', sa.String(length=32), nullable=False),
    sa.Column('amount_tiyin', sa.Integer(), nullable=False),
    sa.Column('billing_period_start', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'billing_period_start', name='uq_payme_receipt_company_period')
    )
    op.create_index(op.f('ix_payme_receipts_company_id'), 'payme_receipts', ['company_id'], unique=False)
    op.create_table('smm_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(length=32), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('shares_count', sa.Integer(), nullable=True),
    sa.Column('saved_count', sa.Integer(), nullable=True),
    sa.Column('follows_count', sa.Integer(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_smm_posts_company_id'), 'smm_posts', ['company_id'], unique=False)
    op.create_index(op.f('ix_smm_posts_platform'), 'smm_posts', ['platform'], unique=False)
    op.create_index(op.f('ix_smm_posts_posted_at'), 'smm_posts', ['posted_at'], unique=False)
    op.create_table('smm_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('media_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'platform', 'date', name='uq_smm_snapshot_company_platform_date')
    )
    op.create_index(op.f('ix_smm_snapshots_company_id'), 'smm_snapshots', ['company_id'], unique=False)
    op.create_index(op.f('ix_smm_snapshots_date'), 'smm_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_smm_snapshots_platform'), 'smm_snapshots', ['platform'], unique=False)
    op.create_table('standing_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.String(length=32), nullable=False),
    sa.Column('time_hhmm', sa.String(length=5), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_sent_date', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standing_reports_chat_id'), 'standing_reports', ['chat_id'], unique=False)
    op.create_index(op.f('ix_standing_reports_company_id'), 'standing_reports', ['company_id'], unique=False)
    op.create_table('standing_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.String(length=32), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=False),
    sa.Column('object_name', sa.String(length=255), nullable=True),
    sa.Column('on_time', sa.String(length=5), nullable=False),
    sa.Column('off_time', sa.String(length=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_desired_state', sa.String(length=8), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_by_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standing_tasks_chat_id'), 'standing_tasks', ['chat_id'], unique=False)
    op.create_index(op.f('ix_standing_tasks_company_id'), 'standing_tasks', ['company_id'], unique=False)
    op.create_table('assistant_unanswered',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('manager_name', sa.String(length=255), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assistant_unanswered_company_id'), 'assistant_unanswered', ['company_id'], unique=False)
    op.create_index(op.f('ix_assistant_unanswered_created_at'), 'assistant_unanswered', ['created_at'], unique=False)
    op.create_table('competitor_ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('page_name', sa.String(length=255), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('snapshot_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('ad_started_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_competitor_ads_company_id'), 'competitor_ads', ['company_id'], unique=False)
    op.create_index(op.f('ix_competitor_ads_competitor_id'), 'competitor_ads', ['competitor_id'], unique=False)
    op.create_table('ig_dm_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('sender', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['ig_dm_conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_ig_dm_messages_company_id'), 'ig_dm_messages', ['company_id'], unique=False)
    op.create_index(op.f('ix_ig_dm_messages_conversation_id'), 'ig_dm_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ig_dm_messages_sent_at'), 'ig_dm_messages', ['sent_at'], unique=False)
    op.create_table('impersonation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_manager_id', sa.Integer(), nullable=False),
    sa.Column('owner_username', sa.String(length=64), nullable=False),
    sa.Column('target_company_id', sa.Integer(), nullable=False),
    sa.Column('target_company_name', sa.String(length=255), nullable=False),
    sa.Column('target_manager_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('ended_reason', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['owner_manager_id'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['target_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['target_manager_id'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impersonation_logs_started_at'), 'impersonation_logs', ['started_at'], unique=False)
    op.create_index(op.f('ix_impersonation_logs_target_company_id'), 'impersonation_logs', ['target_company_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('meta_lead_id', sa.String(length=64), nullable=True),
    sa.Column('campaign_id', sa.String(length=64), nullable=True),
    sa.Column('campaign_name', sa.String(length=255), nullable=True),
    sa.Column('adset_id', sa.String(length=64), nullable=True),
    sa.Column('adset_name', sa.String(length=255), nullable=True),
    sa.Column('ad_id', sa.String(length=64), nullable=True),
    sa.Column('ad_name', sa.String(length=255), nullable=True),
    sa.Column('form_id', sa.String(length=64), nullable=True),
    sa.Column('form_name', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('phone2', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('raw_field_data', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('fbp', sa.String(length=128), nullable=True),
    sa.Column('fbc', sa.String(length=128), nullable=True),
    sa.Column('landing_url', sa.Text(), nullable=True),
    sa.Column('utm_source', sa.String(length=128), nullable=True),
    sa.Column('utm_medium', sa.String(length=128), nullable=True),
    sa.Column('utm_campaign', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('quality_note', sa.Text(), nullable=True),
    sa.Column('sale_amount', sa.Float(), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_manager_id', sa.Integer(), nullable=True),
    sa.Column('next_contact_at', sa.DateTime(), nullable=True),
    sa.Column('next_contact_note', sa.Text(), nullable=True),
    sa.Column('lead_created_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('webhook_delivered_at', sa.DateTime(), nullable=True),
    sa.Column('webhook_delivery_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_manager_id'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meta_lead_id')
    )
    op.create_index('ix_leads_campaign', 'leads', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_leads_campaign_id'), 'leads', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_leads_company_id'), 'leads', ['company_id'], unique=False)
    op.create_index(op.f('ix_leads_form_id'), 'leads', ['form_id'], unique=False)
    op.create_index('ix_leads_next_contact', 'leads', ['next_contact_at'], unique=False)
    op.create_index('ix_leads_status', 'leads', ['status'], unique=False)
    op.create_table('call_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('manager_phone_number', sa.String(length=32), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_audio_data', sa.LargeBinary(), nullable=True),
    sa.Column('uploaded_audio_format', sa.String(length=16), nullable=True),
    sa.Column('ai_overview', sa.Text(), nullable=True),
    sa.Column('ai_score', sa.Integer(), nullable=True),
    sa.Column('ai_status', sa.String(length=16), nullable=True),
    sa.Column('ai_color', sa.String(length=16), nullable=True),
    sa.Column('ai_result', sa.Text(), nullable=True),
    sa.Column('ai_transcription', sa.Text(), nullable=True),
    sa.Column('ai_error', sa.Text(), nullable=True),
    sa.Column('ai_analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('ai_raw_transcription', sa.Text(), nullable=True),
    sa.Column('ai_diarized_json', sa.Text(), nullable=True),
    sa.Column('ai_customer_request', sa.Text(), nullable=True),
    sa.Column('ai_operator_mistakes', sa.Text(), nullable=True),
    sa.Column('ai_positive_points', sa.Text(), nullable=True),
    sa.Column('ai_sale_result', sa.String(length=32), nullable=True),
    sa.Column('ai_callback_required', sa.Boolean(), nullable=True),
    sa.Column('ai_recommended_response', sa.Text(), nullable=True),
    sa.Column('ai_callback_reason', sa.Text(), nullable=True),
    sa.Column('ai_model_transcribe', sa.String(length=64), nullable=True),
    sa.Column('ai_model_analysis', sa.String(length=64), nullable=True),
    sa.Column('ai_audio_channels', sa.Integer(), nullable=True),
    sa.Column('ai_audio_codec', sa.String(length=32), nullable=True),
    sa.Column('ai_audio_duration_sec', sa.Float(), nullable=True),
    sa.Column('ai_stage', sa.String(length=24), nullable=True),
    sa.Column('ai_transcription_quality', sa.String(length=16), nullable=True),
    sa.Column('ai_transcription_confidence', sa.Float(), nullable=True),
    sa.Column('ai_transcription_quality_reasons', sa.Text(), nullable=True),
    sa.Column('ai_transcription_attempts', sa.Integer(), nullable=True),
    sa.Column('ai_transcription_attempts_log', sa.Text(), nullable=True),
    sa.Column('ai_analysis_confidence', sa.Float(), nullable=True),
    sa.Column('ai_score_reasons', sa.Text(), nullable=True),
    sa.Column('ai_operator_channel', sa.Integer(), nullable=True),
    sa.Column('ai_segment_debug_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_call_records_ai_analyzed_at'), 'call_records', ['ai_analyzed_at'], unique=False)
    op.create_index(op.f('ix_call_records_ai_stage'), 'call_records', ['ai_stage'], unique=False)
    op.create_index(op.f('ix_call_records_company_id'), 'call_records', ['company_id'], unique=False)
    op.create_index(op.f('ix_call_records_lead_id'), 'call_records', ['lead_id'], unique=False)
    op.create_index(op.f('ix_call_records_manager_id'), 'call_records', ['manager_id'], unique=False)
    op.create_index(op.f('ix_call_records_phone_number'), 'call_records', ['phone_number'], unique=False)
    op.create_index(op.f('ix_call_records_started_at'), 'call_records', ['started_at'], unique=False)
    op.create_table('lead_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_notes_company_id'), 'lead_notes', ['company_id'], unique=False)
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('sale_number', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('invoice_number', sa.String(length=64), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('is_returned', sa.Boolean(), nullable=False),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_company_id'), 'sales', ['company_id'], unique=False)
    op.create_index(op.f('ix_sales_lead_id'), 'sales', ['lead_id'], unique=False)
    op.create_index(op.f('ix_sales_manager_id'), 'sales', ['manager_id'], unique=False)
    op.create_index(op.f('ix_sales_sold_at'), 'sales', ['sold_at'], unique=False)
    op.create_table('meta_event_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('event_name', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('meta_response_id', sa.String(length=64), nullable=True),
    sa.Column('error_code', sa.Integer(), nullable=True),
    sa.Column('safe_error_message', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_event_logs_company_id'), 'meta_event_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_meta_event_logs_created_at'), 'meta_event_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_meta_event_logs_event_id'), 'meta_event_logs', ['event_id'], unique=False)
    op.create_index(op.f('ix_meta_event_logs_lead_id'), 'meta_event_logs', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meta_event_logs_lead_id'), table_name='meta_event_logs')
    op.drop_index(op.f('ix_meta_event_logs_event_id'), table_name='meta_event_logs')
    op.drop_index(op.f('ix_meta_event_logs_created_at'), table_name='meta_event_logs')
    op.drop_index(op.f('ix_meta_event_logs_company_id'), table_name='meta_event_logs')
    op.drop_table('meta_event_logs')
    op.drop_index(op.f('ix_sales_sold_at'), table_name='sales')
    op.drop_index(op.f('ix_sales_manager_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_lead_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_company_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index(op.f('ix_lead_notes_company_id'), table_name='lead_notes')
    op.drop_table('lead_notes')
    op.drop_index(op.f('ix_call_records_started_at'), table_name='call_records')
    op.drop_index(op.f('ix_call_records_phone_number'), table_name='call_records')
    op.drop_index(op.f('ix_call_records_manager_id'), table_name='call_records')
    op.drop_index(op.f('ix_call_records_lead_id'), table_name='call_records')
    op.drop_index(op.f('ix_call_records_company_id'), table_name='call_records')
    op.drop_index(op.f('ix_call_records_ai_stage'), table_name='call_records')
    op.drop_index(op.f('ix_call_records_ai_analyzed_at'), table_name='call_records')
    op.drop_table('call_records')
    op.drop_index('ix_leads_status', table_name='leads')
    op.drop_index('ix_leads_next_contact', table_name='leads')
    op.drop_index(op.f('ix_leads_form_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_company_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_campaign_id'), table_name='leads')
    op.drop_index('ix_leads_campaign', table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_impersonation_logs_target_company_id'), table_name='impersonation_logs')
    op.drop_index(op.f('ix_impersonation_logs_started_at'), table_name='impersonation_logs')
    op.drop_table('impersonation_logs')
    op.drop_index(op.f('ix_ig_dm_messages_sent_at'), table_name='ig_dm_messages')
    op.drop_index(op.f('ix_ig_dm_messages_conversation_id'), table_name='ig_dm_messages')
    op.drop_index(op.f('ix_ig_dm_messages_company_id'), table_name='ig_dm_messages')
    op.drop_table('ig_dm_messages')
    op.drop_index(op.f('ix_competitor_ads_competitor_id'), table_name='competitor_ads')
    op.drop_index(op.f('ix_competitor_ads_company_id'), table_name='competitor_ads')
    op.drop_table('competitor_ads')
    op.drop_index(op.f('ix_assistant_unanswered_created_at'), table_name='assistant_unanswered')
    op.drop_index(op.f('ix_assistant_unanswered_company_id'), table_name='assistant_unanswered')
    op.drop_table('assistant_unanswered')
    op.drop_index(op.f('ix_standing_tasks_company_id'), table_name='standing_tasks')
    op.drop_index(op.f('ix_standing_tasks_chat_id'), table_name='standing_tasks')
    op.drop_table('standing_tasks')
    op.drop_index(op.f('ix_standing_reports_company_id'), table_name='standing_reports')
    op.drop_index(op.f('ix_standing_reports_chat_id'), table_name='standing_reports')
    op.drop_table('standing_reports')
    op.drop_index(op.f('ix_smm_snapshots_platform'), table_name='smm_snapshots')
    op.drop_index(op.f('ix_smm_snapshots_date'), table_name='smm_snapshots')
    op.drop_index(op.f('ix_smm_snapshots_company_id'), table_name='smm_snapshots')
    op.drop_table('smm_snapshots')
    op.drop_index(op.f('ix_smm_posts_posted_at'), table_name='smm_posts')
    op.drop_index(op.f('ix_smm_posts_platform'), table_name='smm_posts')
    op.drop_index(op.f('ix_smm_posts_company_id'), table_name='smm_posts')
    op.drop_table('smm_posts')
    op.drop_index(op.f('ix_payme_receipts_company_id'), table_name='payme_receipts')
    op.drop_table('payme_receipts')
    op.drop_index(op.f('ix_managers_company_id'), table_name='managers')
    op.drop_table('managers')
    op.drop_index(op.f('ix_ig_dm_conversations_last_message_at'), table_name='ig_dm_conversations')
    op.drop_index(op.f('ix_ig_dm_conversations_customer_ig_id'), table_name='ig_dm_conversations')
    op.drop_index(op.f('ix_ig_dm_conversations_company_id'), table_name='ig_dm_conversations')
    op.drop_table('ig_dm_conversations')
    op.drop_index(op.f('ix_funnel_stages_company_id'), table_name='funnel_stages')
    op.drop_table('funnel_stages')
    op.drop_index(op.f('ix_custom_fields_company_id'), table_name='custom_fields')
    op.drop_table('custom_fields')
    op.drop_index(op.f('ix_competitors_company_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_canned_replies_company_id'), table_name='canned_replies')
    op.drop_table('canned_replies')
    op.drop_table('kv_store')
    op.drop_index(op.f('ix_companies_inbound_lead_token'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
