"""lang.py — 2026-09, foydalanuvchi so'rovi: "сделай на русском, на
узбекском и на всех" (mijozga ko'rinadigan sahifalarni bir necha tilda
qilish). Og'ir Flask-Babel/gettext infratuzilmasi o'rniga eng ODDIY,
tushunarli yondashuv: har bir matn kaliti uchun til-so'zlik (dict).

QAMROV (BOSQICHMA-BOSQICH, foydalanuvchiga aytilgan): 1-bosqichda faqat
"kirish yo'li" sahifalari (landing, login, signup) qamralgan edi. 2-bosqich
(2026-09, "butun ilova o'zbek/rus/ingliz tilida"): ingliz tili qo'shildi,
ICHKI CRM'ning umumiy qobig'i (base.html: sidebar, subnav, AI-yordamchi) va
asosiy CRM sahifalari (dashboard, lidlar, lid tafsiloti, yangi lid, Excel
import, kompaniyalar, menejerlar, menejer faoliyati, profil, qayta aloqa,
sotilgan xaridorlar) tarjima qilindi. Qolgan sahifalar (target/SMM/
analitika/sozlamalar/avtopilot/kreativ va h.k.) va `app.py`dagi
flash()/jsonify() xabarlari -- KEYINGI bosqichlarda.

QOIDALAR:
  * `translate(key, lang, **kwargs)` -- kalit yoki til topilmasa avtomatik
    o'zbekchaga qaytadi, HECH QACHON xato bermaydi. `kwargs` berilsa matn
    `.format(**kwargs)` bilan to'ldiriladi ("{n} ta lid") -- placeholder
    yetishmasa ham xato bermaydi, xom matn qaytadi.
  * O'zbekcha matn -- ASL matn bilan AYNAN bir xil (mavjud foydalanuvchi
    uchun hech narsa o'zgarmaydi); ruscha/inglizcha -- tabiiy, so'zma-so'z
    emas.
  * HTML entity (`&middot;`, `&rarr;`) O'RNIGA unicode belgi (·, →) yoziladi
    -- Jinja autoescape entity'ni buzib yuboradi. Ichida HTML bo'lgan
    matnlar (masalan `<strong>`) shablonda `|safe` bilan chiqariladi va
    ularga faqat RAQAM yoki oldindan `|e` qilingan qiymat qo'yiladi.
  * onsubmit/confirm() kabi JS-kontekstda: `{{ t('...')|tojson|forceescape }}`
    (atribut ichida), `<script>` ichida esa `{{ t('...')|tojson }}`.

YANGI KALIT QO'SHISH: pastdagi `_APP_STRINGS` jadvaliga BITTA qatorda
(kalit, uz, ru, en) to'rtligini qo'shing -- uchala til yonma-yon turgani
uchun birortasi unutilib qolmaydi (import paytida `TRANSLATIONS`ga
qo'shiladi). Eski uslub (har til uchun alohida dict) landing/login/signup
kalitlari uchun saqlab qolingan."""

SUPPORTED_LANGS = ["uz", "ru", "en"]
DEFAULT_LANG = "uz"

LANG_LABELS = {"uz": "O'zbekcha", "ru": "Русский", "en": "English"}

TRANSLATIONS = {
    "uz": {
        "nav.features": "Imkoniyatlar",
        "nav.how": "Qanday ishlaydi",
        "nav.pricing": "Tariflar",
        "nav.login": "Kirish",
        "nav.signup": "Bepul boshlash",
        "nav.home": "Bosh sahifa",

        "hero.eyebrow": "O'zbekiston bizneslari uchun CRM",
        "hero.h1": "5-6 ta xizmat o'rniga — <span>bitta</span> Replix",
        "hero.sub": "CRM, reklama monitoring, SMM hisobot, qo'ng'iroq nazorati va AI tahlil uchun alohida-alohida xizmatlarga to'lash shart emas. Replix hammasini BITTA obunada, ancha arzon narxda birlashtiradi — Instagram va Facebook reklamalaringizni, sotuv jamoangizni va mijozlar bazangizni bitta joyda kuzating.",
        "hero.cta_trial": "5 kun bepul sinash",
        "hero.cta_pricing": "Tariflarni ko'rish",
        "hero.note1": "✓ Karta shart emas",
        "hero.note2": "✓ 5 daqiqada ishga tushiriladi",
        "hero.note3": "✓ O'zbek tilida to'liq qo'llab-quvvatlash",

        "compare.h2": "Nega 5 ta alohida xizmat o'rniga bitta Replix?",
        "compare.sub": "Odatda CRM, reklama monitoring, SMM hisobot va qo'ng'iroq tahlili — har biri ALOHIDA xizmat, alohida login, alohida to'lov. Replix'da hammasi bitta obunada.",
        "compare.separate_head": "Alohida-alohida sotib olsangiz",
        "compare.replix_head": "Replix bilan",
        "compare.total_separate": "Taxminan $140–270/oy + har biriga alohida sozlash va login",
        "compare.total_replix": "$50/oy dan boshlanadi — bitta login, bitta hisobot",
        "compare.item1": "CRM / lidlar tizimi",
        "compare.item1_price": "~$30–50/oy",
        "compare.item2": "Reklama (target) monitoring",
        "compare.item2_price": "~$40–80/oy",
        "compare.item3": "SMM hisobot xizmati",
        "compare.item3_price": "~$20–40/oy",
        "compare.item4": "AI qo'ng'iroq tahlili",
        "compare.item4_price": "~$50–100/oy",

        "features.h2": "Bitta tizim — butun sotuv jarayoni",
        "features.sub": "Alohida-alohida jadval va Excel fayllar o'rniga, reklamadan sotuvgacha bo'lgan yo'lning har bosqichi shu yerda.",
        "features.f1_title": "Lidlar va CRM voronkasi",
        "features.f1_desc": "Meta Lead Ads'dan avtomatik kelgan va qo'lda kiritilgan lidlarni bitta voronkada boshqaring: yangi → aloqa qilindi → malakali → sotildi.",
        "features.f2_title": "Target monitoring",
        "features.f2_desc": "Xarajat, lead soni, CPL va konversiya — kampaniya kesimida, real vaqtda. Byudjet oshib ketishidan oldin ogohlantirish oladi.",
        "features.f3_title": "SMM hisobot va Instagram xabarlar",
        "features.f3_desc": "Obunachilar dinamikasi, kontent samaradorligi va Instagram Direct xabarlar bitta joyda — javobsiz qolgan mijoz yo'qolmaydi.",
        "features.f4_title": "AI qo'ng'iroq tahlili",
        "features.f4_desc": "Har bir sotuv qo'ng'irog'i avtomatik tinglanadi va tahlil qilinadi — sifat balli, kamchiliklar va tavsiyalar bilan (Biznes va Ekspert tarifida).",
        "features.f5_title": "Menejerlar KPI va bonus",
        "features.f5_desc": "Har oy avtomatik hisoblanadigan reja-bajarilish jadvali — kim qancha sotdi, bonus qancha bo'lishi bir qarashda ko'rinadi.",
        "features.f6_title": "Telegram bot orqali hisobot",
        "features.f6_desc": "Kuniga bir marta, jamoangiz Telegram guruhiga avtomatik yuboriladigan holat hisoboti — hech kim CRM'ni ochmasa ham xabardor bo'ladi.",

        "steps.h2": "4 qadamda ishga tushiring",
        "steps.sub": "Alohida sozlash mutaxassisi kerak emas — ro'yxatdan o'tgach, o'zingiz 5-10 daqiqada tayyorlaysiz.",
        "steps.s1_title": "Ro'yxatdan o'ting",
        "steps.s1_desc": "Kompaniya nomi, login va parol — shu qadar, karta kerak emas.",
        "steps.s2_title": "Akkauntingizni ulang",
        "steps.s2_desc": "Instagram (va tarifga qarab Facebook reklama hisobingizni) ulang.",
        "steps.s3_title": "Jamoangizni qo'shing",
        "steps.s3_desc": "Menejerlaringizga login yarating, kimga qaysi bo'lim ochiq ekanini belgilang.",
        "steps.s4_title": "Natijalarni kuzating",
        "steps.s4_desc": "Lidlar, xarajat va sotuvlar real vaqtda bir ekranda to'planadi.",

        "pricing.h2": "Har bosqich uchun aniq tarif",
        "pricing.sub": "Sinovdan boshlang, jamoangiz o'sgani sayin tarifni oshiring — yashirin to'lov yo'q.",
        "pricing.badge_popular": "Eng ommabop",
        "pricing.cta_trial": "Bepul boshlash",
        "pricing.cta_signup": "Ro'yxatdan o'tish",
        "pricing.free": "Bepul",
        "pricing.per_month": "/oy",
        "pricing.monthly_renew": "har oy yangilanadi",
        "pricing.days": "kun",

        "cta_band.h2": "Reklama byudjetingiz oqilona ishlayaptimi?",
        "cta_band.sub": "Bugun ro'yxatdan o'ting, Instagram akkauntingizni ulang va birinchi natijalarni bugunoq ko'ring.",
        "cta_band.button": "5 kun bepul boshlash",

        "footer.rights": "Barcha huquqlar himoyalangan.",
        "footer.login": "Kirish",

        "mock.new_leads": "Yangi lidlar",
        "mock.cpl": "CPL",
        "mock.sales": "Sotuv",
        "mock.status_sold": "sotildi",
        "mock.status_qualified": "malakali",
        "mock.status_contacted": "aloqa qilindi",
        "mock.status_new": "yangi",

        "login.subtitle": "Kirish uchun login/parolingizni kiriting",
        "login.username": "Login",
        "login.password": "Parol",
        "login.submit": "Kirish",
        "login.no_account": "Hali kompaniyangiz yo'qmi?",
        "login.signup_link": "Ro'yxatdan o'ting",

        "signup.title": "Kompaniyangizni ro'yxatdan o'tkazing",
        "signup.subtitle": "2 daqiqada tayyor bo'ladi — keyingi qadamda Instagram akkauntingizni ulaysiz.",
        "signup.choose_plan": "Tarifni tanlang",
        "signup.company_name": "Kompaniya nomi",
        "signup.admin_username": "Admin login",
        "signup.admin_full_name": "To'liq ism (ixtiyoriy)",
        "signup.email": "Email (ixtiyoriy)",
        "signup.password": "Parol",
        "signup.password2": "Parolni tasdiqlang",
        "signup.submit": "Ro'yxatdan o'tish",
        "signup.have_account": "Allaqachon hisobingiz bormi?",
        "signup.login_link": "Kirish",

        # 2026-09, SEO/AEO tuzatish: foydalanuvchi so'rovi ("ai qidirganda
        # ideal chiqishi uchun kriteriyalar bo'yicha yoz"). Google AI
        # Overview replix.uz so'rovida bog'liq bo'lmagan "Replix.ai" (AI matn
        # yozish xizmati) va "Ecom Learn by Replix" (kurs platformasi) kabi
        # BOSHQA "Replix" nomli mahsulotlarni aralashtirib yuborgani
        # aniqlandi -- chunki "Replix" nomi internetda bir nechta turli
        # kompaniyaga tegishli. Bu FAQ blok ANIQ, deklarativ javoblar bilan
        # o'zini his qilib, o'sha boshqa mahsulotlardan farqlaydi (bu --
        # "disambiguation" -- qidiruv/AI tizimlariga to'g'ri obyektni
        # ko'rsatishning tan olingan usuli).
        "faq.q1": "Replix nima?",
        "faq.a1": "Replix — O'zbekiston bizneslari uchun CRM, Meta (Instagram/Facebook) reklama monitoring, SMM hisobot va AI qo'ng'iroq tahlili xizmatlarini BITTA platformada birlashtiruvchi tizim. U reklama byudjeti, lidlar va sotuv jamoasini reklamadan sotuvgacha bitta ekranda kuzatib borishga yordam beradi.",
        "faq.q2": "Replix kimlar uchun mo'ljallangan?",
        "faq.a2": "Instagram va Facebook orqali reklama beradigan O'zbekiston kichik va o'rta bizneslari uchun — sotuv jamoasi, reklama xarajati va mijozlar bazasini bitta joyda ko'rishni istaydiganlar uchun.",
        "faq.q3": "Replix qancha turadi?",
        "faq.a3": "Narxlar oyiga $50 dan boshlanadi. 5 kunlik bepul sinov mavjud, karta ma'lumoti talab qilinmaydi.",
        "faq.q4": "Replix.uz \"Replix.ai\" yoki boshqa \"Replix\" nomli xizmatlar bilan bog'liqmi?",
        "faq.a4": "Yo'q. Replix (replix.uz) — O'zbekistonda ishlab chiqilgan, CRM va Meta reklama monitoringga ixtisoslashgan alohida platforma. U matn/kontent yozuvchi AI-yordamchilar yoki boshqa davlatlardagi kurs platformalari bilan hech qanday aloqasi yo'q — bu butunlay boshqa kompaniya va mahsulot.",
        "faq.q5": "Instagram yoki Facebook akkauntimni qanday ulayman?",
        "faq.a5": "Ro'yxatdan o'tgach, \"Akkauntlarni ulash\" sahifasida bitta tugma orqali Facebook hisobingizga kirasiz — sahifa ID yoki token qo'lda kiritish shart emas.",

        # 2026-09, foydalanuvchi so'rovi ("web ozida ushatta pasida forma
        # qilib qoy ... aloqa uchun nomerlar ham qoshib qoy"): bosh sahifa
        # pastidagi "Biz bilan bog'laning" bo'limi uchun.
        "contact.h2": "Biz bilan bog'laning",
        "contact.sub": "Savolingiz bormi? Telefon yoki Telegram orqali yozing, yoki quyidagi formani to'ldiring — tez orada javob beramiz.",
        "contact.note": "Formani to'ldiring — odatda 1 soat ichida siz bilan bog'lanamiz.",
        "contact.name": "Ismingiz",
        "contact.phone": "Telefon raqamingiz",
        "contact.message": "Xabar (ixtiyoriy)",
        "contact.submit": "Yuborish",
    },
    "ru": {
        "nav.features": "Возможности",
        "nav.how": "Как это работает",
        "nav.pricing": "Тарифы",
        "nav.login": "Войти",
        "nav.signup": "Начать бесплатно",
        "nav.home": "Главная",

        "hero.eyebrow": "CRM для бизнеса в Узбекистане",
        "hero.h1": "5-6 сервисов — теперь <span>один</span> Replix",
        "hero.sub": "Не нужно платить отдельно за CRM, мониторинг рекламы, SMM-отчёты, контроль звонков и AI-анализ. Replix объединяет всё это в ОДНОЙ подписке по значительно более низкой цене — отслеживайте рекламу в Instagram и Facebook, отдел продаж и базу клиентов в одном месте.",
        "hero.cta_trial": "5 дней бесплатно",
        "hero.cta_pricing": "Смотреть тарифы",
        "hero.note1": "✓ Карта не нужна",
        "hero.note2": "✓ Запуск за 5 минут",
        "hero.note3": "✓ Полная поддержка на узбекском и русском",

        "compare.h2": "Зачем 5 отдельных сервисов, если можно один?",
        "compare.sub": "Обычно CRM, мониторинг рекламы, SMM-отчёты и анализ звонков — это ОТДЕЛЬНЫЕ сервисы: отдельный вход, отдельная оплата. В Replix всё в одной подписке.",
        "compare.separate_head": "Если покупать по отдельности",
        "compare.replix_head": "С Replix",
        "compare.total_separate": "Примерно $140–270/мес + отдельная настройка и вход для каждого",
        "compare.total_replix": "От $50/мес — один вход, один отчёт",
        "compare.item1": "CRM / система лидов",
        "compare.item1_price": "~$30–50/мес",
        "compare.item2": "Мониторинг рекламы (target)",
        "compare.item2_price": "~$40–80/мес",
        "compare.item3": "Сервис SMM-отчётов",
        "compare.item3_price": "~$20–40/мес",
        "compare.item4": "AI-анализ звонков",
        "compare.item4_price": "~$50–100/мес",

        "features.h2": "Одна система — весь процесс продаж",
        "features.sub": "Вместо отдельных таблиц и файлов Excel — каждый этап пути от рекламы до продажи здесь.",
        "features.f1_title": "Лиды и воронка CRM",
        "features.f1_desc": "Управляйте лидами, автоматически пришедшими из Meta Lead Ads и введёнными вручную, в одной воронке: новый → на связи → квалифицирован → продан.",
        "features.f2_title": "Мониторинг рекламы",
        "features.f2_desc": "Расход, число лидов, CPL и конверсия — в разрезе кампаний, в реальном времени. Предупреждение до превышения бюджета.",
        "features.f3_title": "SMM-отчёты и сообщения Instagram",
        "features.f3_desc": "Динамика подписчиков, эффективность контента и сообщения Instagram Direct в одном месте — ни один клиент без ответа не потеряется.",
        "features.f4_title": "AI-анализ звонков",
        "features.f4_desc": "Каждый звонок продажи автоматически прослушивается и анализируется — с оценкой качества, недочётами и рекомендациями (в тарифах Бизнес и Эксперт).",
        "features.f5_title": "KPI и бонусы менеджеров",
        "features.f5_desc": "Автоматически рассчитываемый ежемесячный план-факт — сразу видно, кто сколько продал и какой будет бонус.",
        "features.f6_title": "Отчёт через Telegram-бота",
        "features.f6_desc": "Раз в день автоматический отчёт о статусе отправляется в Telegram-группу вашей команды — все в курсе, даже не открывая CRM.",

        "steps.h2": "Запуск за 4 шага",
        "steps.sub": "Отдельный специалист по настройке не нужен — после регистрации вы сами всё подготовите за 5-10 минут.",
        "steps.s1_title": "Зарегистрируйтесь",
        "steps.s1_desc": "Название компании, логин и пароль — и всё, карта не нужна.",
        "steps.s2_title": "Подключите аккаунт",
        "steps.s2_desc": "Подключите Instagram (и, в зависимости от тарифа, рекламный аккаунт Facebook).",
        "steps.s3_title": "Добавьте команду",
        "steps.s3_desc": "Создайте логины для менеджеров, укажите, какой раздел кому доступен.",
        "steps.s4_title": "Следите за результатами",
        "steps.s4_desc": "Лиды, расходы и продажи собираются на одном экране в реальном времени.",

        "pricing.h2": "Понятный тариф для каждого этапа",
        "pricing.sub": "Начните с пробного периода, повышайте тариф по мере роста команды — никаких скрытых платежей.",
        "pricing.badge_popular": "Популярный выбор",
        "pricing.cta_trial": "Начать бесплатно",
        "pricing.cta_signup": "Зарегистрироваться",
        "pricing.free": "Бесплатно",
        "pricing.per_month": "/мес",
        "pricing.monthly_renew": "продлевается ежемесячно",
        "pricing.days": "дней",

        "cta_band.h2": "Ваш рекламный бюджет работает разумно?",
        "cta_band.sub": "Зарегистрируйтесь сегодня, подключите Instagram и увидите первые результаты уже сегодня.",
        "cta_band.button": "Начать бесплатно на 5 дней",

        "footer.rights": "Все права защищены.",
        "footer.login": "Войти",

        "mock.new_leads": "Новые лиды",
        "mock.cpl": "CPL",
        "mock.sales": "Продажи",
        "mock.status_sold": "продано",
        "mock.status_qualified": "квалифицирован",
        "mock.status_contacted": "на связи",
        "mock.status_new": "новый",

        "login.subtitle": "Введите логин/пароль для входа",
        "login.username": "Логин",
        "login.password": "Пароль",
        "login.submit": "Войти",
        "login.no_account": "Ещё нет компании?",
        "login.signup_link": "Зарегистрироваться",

        "signup.title": "Зарегистрируйте свою компанию",
        "signup.subtitle": "Займёт 2 минуты — на следующем шаге вы подключите Instagram.",
        "signup.choose_plan": "Выберите тариф",
        "signup.company_name": "Название компании",
        "signup.admin_username": "Логин администратора",
        "signup.admin_full_name": "Полное имя (необязательно)",
        "signup.email": "Email (необязательно)",
        "signup.password": "Пароль",
        "signup.password2": "Подтвердите пароль",
        "signup.submit": "Зарегистрироваться",
        "signup.have_account": "Уже есть аккаунт?",
        "signup.login_link": "Войти",

        "faq.q1": "Что такое Replix?",
        "faq.a1": "Replix — это система для бизнеса в Узбекистане, объединяющая CRM, мониторинг рекламы Meta (Instagram/Facebook), SMM-отчёты и AI-анализ звонков в ОДНОЙ платформе. Она помогает отслеживать рекламный бюджет, лиды и отдел продаж на одном экране — от рекламы до продажи.",
        "faq.q2": "Для кого предназначен Replix?",
        "faq.a2": "Для малого и среднего бизнеса в Узбекистане, который даёт рекламу в Instagram и Facebook — для тех, кто хочет видеть отдел продаж, расходы на рекламу и базу клиентов в одном месте.",
        "faq.q3": "Сколько стоит Replix?",
        "faq.a3": "Тарифы начинаются от $50 в месяц. Доступен 5-дневный бесплатный пробный период, банковская карта не требуется.",
        "faq.q4": "Связан ли Replix.uz с «Replix.ai» или другими сервисами с названием «Replix»?",
        "faq.a4": "Нет. Replix (replix.uz) — отдельная платформа, разработанная в Узбекистане и специализирующаяся на CRM и мониторинге рекламы Meta. Она никак не связана с AI-помощниками для написания текстов или курс-платформами с похожим названием в других странах — это совершенно другая компания и продукт.",
        "faq.q5": "Как подключить аккаунт Instagram или Facebook?",
        "faq.a5": "После регистрации на странице «Подключение аккаунтов» вы входите в свой аккаунт Facebook одной кнопкой — вводить ID страницы или токен вручную не нужно.",

        "contact.h2": "Свяжитесь с нами",
        "contact.sub": "Есть вопрос? Напишите по телефону или в Telegram, либо заполните форму ниже — ответим в ближайшее время.",
        "contact.note": "Заполните форму — обычно отвечаем в течение 1 часа.",
        "contact.name": "Ваше имя",
        "contact.phone": "Номер телефона",
        "contact.message": "Сообщение (необязательно)",
        "contact.submit": "Отправить",
    },
    # 2026-09, 2-bosqich: ingliz tili (marketing uslubida, so'zma-so'z emas).
    "en": {
        "nav.features": "Features",
        "nav.how": "How it works",
        "nav.pricing": "Pricing",
        "nav.login": "Log in",
        "nav.signup": "Start for free",
        "nav.home": "Home",

        "hero.eyebrow": "CRM for businesses in Uzbekistan",
        "hero.h1": "Instead of 5-6 tools — <span>one</span> Replix",
        "hero.sub": "Stop paying separately for a CRM, ad monitoring, SMM reports, call control and AI analysis. Replix brings all of it into ONE subscription at a far lower price — track your Instagram and Facebook ads, your sales team and your customer base in one place.",
        "hero.cta_trial": "Try free for 5 days",
        "hero.cta_pricing": "See pricing",
        "hero.note1": "✓ No card required",
        "hero.note2": "✓ Up and running in 5 minutes",
        "hero.note3": "✓ Full support in Uzbek, Russian and English",

        "compare.h2": "Why one Replix instead of 5 separate tools?",
        "compare.sub": "A CRM, ad monitoring, SMM reports and call analysis are usually SEPARATE services — separate logins, separate bills. With Replix it's all one subscription.",
        "compare.separate_head": "Bought separately",
        "compare.replix_head": "With Replix",
        "compare.total_separate": "Roughly $140–270/mo + separate setup and login for each",
        "compare.total_replix": "From $50/mo — one login, one report",
        "compare.item1": "CRM / lead system",
        "compare.item1_price": "~$30–50/mo",
        "compare.item2": "Ad (targeting) monitoring",
        "compare.item2_price": "~$40–80/mo",
        "compare.item3": "SMM reporting service",
        "compare.item3_price": "~$20–40/mo",
        "compare.item4": "AI call analysis",
        "compare.item4_price": "~$50–100/mo",

        "features.h2": "One system — the whole sales process",
        "features.sub": "Instead of scattered spreadsheets and Excel files, every step from ad to sale lives here.",
        "features.f1_title": "Leads and CRM funnel",
        "features.f1_desc": "Manage leads that arrive automatically from Meta Lead Ads and those entered by hand in one funnel: new → contacted → qualified → sold.",
        "features.f2_title": "Ad monitoring",
        "features.f2_desc": "Spend, lead count, CPL and conversion — per campaign, in real time. Get alerted before the budget runs over.",
        "features.f3_title": "SMM reports and Instagram messages",
        "features.f3_desc": "Follower growth, content performance and Instagram Direct messages in one place — no unanswered customer gets lost.",
        "features.f4_title": "AI call analysis",
        "features.f4_desc": "Every sales call is automatically transcribed and reviewed — with a quality score, weak points and recommendations (Business and Expert plans).",
        "features.f5_title": "Manager KPIs and bonuses",
        "features.f5_desc": "A plan-vs-actual table calculated automatically every month — who sold how much and what the bonus will be, at a glance.",
        "features.f6_title": "Reports via Telegram bot",
        "features.f6_desc": "Once a day, a status report is sent automatically to your team's Telegram group — everyone stays informed even without opening the CRM.",

        "steps.h2": "Get started in 4 steps",
        "steps.sub": "No setup specialist needed — after signing up you'll have it ready yourself in 5-10 minutes.",
        "steps.s1_title": "Sign up",
        "steps.s1_desc": "Company name, login and password — that's it, no card needed.",
        "steps.s2_title": "Connect your account",
        "steps.s2_desc": "Connect Instagram (and, depending on your plan, your Facebook ad account).",
        "steps.s3_title": "Add your team",
        "steps.s3_desc": "Create logins for your managers and choose which sections each one can see.",
        "steps.s4_title": "Track results",
        "steps.s4_desc": "Leads, spend and sales come together on one screen in real time.",

        "pricing.h2": "A clear plan for every stage",
        "pricing.sub": "Start with a trial and move up as your team grows — no hidden fees.",
        "pricing.badge_popular": "Most popular",
        "pricing.cta_trial": "Start for free",
        "pricing.cta_signup": "Sign up",
        "pricing.free": "Free",
        "pricing.per_month": "/mo",
        "pricing.monthly_renew": "renews monthly",
        "pricing.days": "days",

        "cta_band.h2": "Is your ad budget working smart?",
        "cta_band.sub": "Sign up today, connect your Instagram account and see your first results the same day.",
        "cta_band.button": "Start 5 days free",

        "footer.rights": "All rights reserved.",
        "footer.login": "Log in",

        "mock.new_leads": "New leads",
        "mock.cpl": "CPL",
        "mock.sales": "Sales",
        "mock.status_sold": "sold",
        "mock.status_qualified": "qualified",
        "mock.status_contacted": "contacted",
        "mock.status_new": "new",

        "login.subtitle": "Enter your login and password to sign in",
        "login.username": "Login",
        "login.password": "Password",
        "login.submit": "Log in",
        "login.no_account": "Don't have a company yet?",
        "login.signup_link": "Sign up",

        "signup.title": "Register your company",
        "signup.subtitle": "Takes 2 minutes — you'll connect your Instagram account in the next step.",
        "signup.choose_plan": "Choose a plan",
        "signup.company_name": "Company name",
        "signup.admin_username": "Admin login",
        "signup.admin_full_name": "Full name (optional)",
        "signup.email": "Email (optional)",
        "signup.password": "Password",
        "signup.password2": "Confirm password",
        "signup.submit": "Sign up",
        "signup.have_account": "Already have an account?",
        "signup.login_link": "Log in",

        "faq.q1": "What is Replix?",
        "faq.a1": "Replix is a platform for businesses in Uzbekistan that combines a CRM, Meta (Instagram/Facebook) ad monitoring, SMM reports and AI call analysis in ONE place. It helps you track your ad budget, leads and sales team on a single screen — from ad to sale.",
        "faq.q2": "Who is Replix for?",
        "faq.a2": "Small and medium businesses in Uzbekistan that advertise on Instagram and Facebook — anyone who wants to see their sales team, ad spend and customer base in one place.",
        "faq.q3": "How much does Replix cost?",
        "faq.a3": "Plans start at $50 per month. A 5-day free trial is available, no card details required.",
        "faq.q4": "Is Replix.uz related to \"Replix.ai\" or other services named \"Replix\"?",
        "faq.a4": "No. Replix (replix.uz) is a standalone platform built in Uzbekistan, specialising in CRM and Meta ad monitoring. It has no connection to AI writing assistants or course platforms with a similar name in other countries — it is an entirely different company and product.",
        "faq.q5": "How do I connect my Instagram or Facebook account?",
        "faq.a5": "After signing up, go to the \"Connect accounts\" page and log in to your Facebook account with a single button — no need to enter page IDs or tokens by hand.",

        "contact.h2": "Get in touch",
        "contact.sub": "Have a question? Reach us by phone or Telegram, or fill in the form below — we'll get back to you shortly.",
        "contact.note": "Fill in the form — we usually get back to you within an hour.",
        "contact.name": "Your name",
        "contact.phone": "Your phone number",
        "contact.message": "Message (optional)",
        "contact.submit": "Send",
    },
}


# ---------------------------------------------------------------------------
# 2026-09, 2-bosqich: ICHKI CRM matnlari. Har qator -- (kalit, uz, ru, en).
# Uchala til yonma-yon: birorta tilda kalit tushib qolishi mumkin emas.
# `{n}`, `{name}` kabi placeholder'lar `translate(..., n=5)` bilan to'ldiriladi.
# ---------------------------------------------------------------------------
_APP_STRINGS = [
    # ---- Umumiy (bir nechta sahifada takrorlanadigan qisqa so'zlar) ----
    ("common.save", "Saqlash", "Сохранить", "Save"),
    ("common.add", "Qo'shish", "Добавить", "Add"),
    ("common.edit", "Tahrirlash", "Редактировать", "Edit"),
    ("common.delete", "O'chirish", "Удалить", "Delete"),
    ("common.close", "Yopish", "Закрыть", "Close"),
    ("common.all", "Hammasi", "Все", "All"),
    ("common.som", "so'm", "сум", "UZS"),

    # ---- Sana oralig'i presetlari (dashboard, lidlar, menejer faoliyati) ----
    ("period.today", "Bugun", "Сегодня", "Today"),
    ("period.yesterday", "Kecha", "Вчера", "Yesterday"),
    ("period.this_week", "Shu hafta", "Эта неделя", "This week"),
    ("period.last_week", "O'tgan hafta", "Прошлая неделя", "Last week"),
    ("period.this_month", "Shu oy", "Этот месяц", "This month"),
    ("period.last_month", "O'tgan oy", "Прошлый месяц", "Last month"),
    ("period.this_year", "Shu yil", "Этот год", "This year"),
    ("period.last_7d_short", "7 kun", "7 дней", "7 days"),
    ("period.last_30d_short", "30 kun", "30 дней", "30 days"),
    ("period.last_90d_short", "90 kun", "90 дней", "90 days"),
    ("period.last_7d", "So'nggi 7 kun", "Последние 7 дней", "Last 7 days"),
    ("period.last_30d", "So'nggi 30 kun", "Последние 30 дней", "Last 30 days"),
    ("period.last_90d", "So'nggi 90 kun", "Последние 90 дней", "Last 90 days"),
    ("period.maximum", "Maksimal", "Максимум", "Maximum"),

    # ---- base.html: umumiy qobiq (meta, sidebar, subnav, AI-yordamchi) ----
    ("shell.meta_description",
     "Replix — Instagram va Facebook reklamangizni, CRM'ingizni, SMM hisobotingizni va AI qo'ng'iroq tahlilingizni bitta tizimda birlashtiruvchi platforma. 5 kun bepul sinov.",
     "Replix — платформа, объединяющая рекламу в Instagram и Facebook, CRM, SMM-отчёты и AI-анализ звонков в одной системе. 5 дней бесплатно.",
     "Replix — one platform for your Instagram and Facebook ads, CRM, SMM reports and AI call analysis. 5-day free trial."),
    ("shell.og_title",
     "Replix — reklama, CRM va AI tahlil bitta tizimda",
     "Replix — реклама, CRM и AI-анализ в одной системе",
     "Replix — ads, CRM and AI analysis in one system"),
    ("shell.og_description",
     "Instagram/Facebook reklama monitoring, lidlar CRM'i, SMM hisobot va AI qo'ng'iroq tahlili — bitta obunada, $20/oydan.",
     "Мониторинг рекламы Instagram/Facebook, CRM для лидов, SMM-отчёты и AI-анализ звонков — в одной подписке, от $20/мес.",
     "Instagram/Facebook ad monitoring, lead CRM, SMM reports and AI call analysis — one subscription, from $20/mo."),
    ("shell.menu", "Menyu", "Меню", "Menu"),
    ("shell.nav_dashboard", "Dashboard", "Дашборд", "Dashboard"),
    ("shell.nav_crm", "CRM", "CRM", "CRM"),
    ("shell.nav_monitoring", "Monitoring", "Мониторинг", "Monitoring"),
    ("shell.nav_marketing", "Marketing", "Маркетинг", "Marketing"),
    ("shell.nav_marketing_tip", "Marketing (Target, SMM)", "Маркетинг (таргет, SMM)", "Marketing (Ads, SMM)"),
    ("shell.nav_autopilot", "Avtopilot", "Автопилот", "Autopilot"),
    ("shell.nav_autopilot_tip", "Avtopilot (Meta Ads)", "Автопилот (Meta Ads)", "Autopilot (Meta Ads)"),
    ("shell.nav_creative", "Kreativ studiya", "Креатив-студия", "Creative studio"),
    ("shell.nav_creative_tip", "Kreativ studiya (AI rasm)", "Креатив-студия (AI-изображения)", "Creative studio (AI images)"),
    ("shell.nav_lead_analytics", "Lead Analytics", "Аналитика лидов", "Lead Analytics"),
    ("shell.nav_chat", "Chat", "Чат", "Chat"),
    ("shell.nav_competitors", "Raqobatchilar", "Конкуренты", "Competitors"),
    ("shell.nav_management", "Boshqaruv", "Управление", "Management"),
    ("shell.nav_connection", "Connection", "Подключения", "Connection"),
    ("shell.upsell_title", "Tarifni oshirish", "Повысить тариф", "Upgrade plan"),
    ("shell.plan_label", "{plan} tarif", "Тариф {plan}", "{plan} plan"),
    ("shell.days_left", "{n} kun qoldi", "осталось {n} дн.", "{n} days left"),
    ("shell.upgrade_to", "{plan}ga o'ting →", "Перейти на {plan} →", "Upgrade to {plan} →"),
    ("shell.my_profile", "Mening profilim", "Мой профиль", "My profile"),
    ("shell.theme_dark", "Qorong'i rejim", "Тёмная тема", "Dark mode"),
    ("shell.theme_light", "Yorug' rejim", "Светлая тема", "Light mode"),
    ("shell.theme_toggle", "Mavzuni almashtirish", "Переключить тему", "Switch theme"),
    ("shell.logout", "Chiqish", "Выйти", "Log out"),
    ("shell.pin_menu", "Menyuni mahkamlash", "Закрепить меню", "Pin menu"),
    ("shell.collapse", "Yig'ish", "Свернуть", "Collapse"),
    ("shell.language", "Til", "Язык", "Language"),
    ("shell.impersonating",
     "Siz hozir <b>«{name}»</b> nomidan ko'ryapsiz.",
     "Сейчас вы просматриваете от имени <b>«{name}»</b>.",
     "You are currently viewing as <b>“{name}”</b>."),
    ("shell.impersonation_exit", "Chiqish", "Выйти", "Exit"),
    ("shell.sub_leads", "Lidlar", "Лиды", "Leads"),
    ("shell.sub_sold", "Sotilgan xaridorlar", "Покупатели", "Sold customers"),
    ("shell.sub_followups", "Qayta aloqa", "Повторный контакт", "Follow-ups"),
    ("shell.sub_manager_activity", "Menejer faoliyati", "Активность менеджеров", "Manager activity"),
    ("shell.sub_analytics", "Analitika", "Аналитика", "Analytics"),
    ("shell.sub_audio", "Audio", "Аудио", "Audio"),
    ("shell.sub_target", "Target", "Таргет", "Ads"),
    ("shell.sub_smm", "SMM hisobot", "SMM-отчёт", "SMM report"),
    ("shell.sub_settings", "Sozlamalar", "Настройки", "Settings"),
    ("shell.sub_managers", "Menejerlar", "Менеджеры", "Managers"),
    ("shell.sub_billing", "Tarif va to'lov", "Тариф и оплата", "Plan & billing"),
    ("shell.sub_companies", "Kompaniyalar", "Компании", "Companies"),
    ("shell.sub_general", "Umumiy", "Общие", "General"),
    ("shell.sub_business_profile", "Kompaniya ma'lumotlari", "Данные компании", "Company details"),
    ("shell.sub_brand_kit", "Brend kit", "Бренд-кит", "Brand kit"),
    ("shell.sub_cpl", "CPL chegaralari", "Лимиты CPL", "CPL limits"),
    ("shell.sub_telegram", "Telegram", "Telegram", "Telegram"),
    ("shell.sub_modules", "Funksiyalar", "Функции", "Features"),
    ("shell.sub_ai", "AI", "AI", "AI"),
    ("shell.sub_unanswered", "Javobsiz savollar", "Вопросы без ответа", "Unanswered questions"),
    ("shell.sub_funnel", "Voronka", "Воронка", "Funnel"),
    ("shell.sub_custom_fields", "Kvalifikatsiya savollari", "Вопросы квалификации", "Qualification questions"),
    ("shell.sub_standing_tasks", "Doimiy vazifalar", "Постоянные задачи", "Standing tasks"),
    ("shell.ai_nudge_title", "Biznesingiz haqida hali tanishmadik! 👋", "Мы ещё не познакомились с вашим бизнесом! 👋", "We haven't met your business yet! 👋"),
    ("shell.ai_nudge_text",
     "2 daqiqada bir nechta savolga javob bering — shundan keyin men SIZNING biznesingizga mos, aniq maslahat bera boshlayman (umumiy javob emas).",
     "Ответьте на несколько вопросов за 2 минуты — после этого я начну давать точные советы именно для ВАШЕГО бизнеса (а не общие ответы).",
     "Answer a few questions in 2 minutes — after that I'll start giving precise advice tailored to YOUR business (not generic answers)."),
    ("shell.ai_nudge_cta", "Tanishtirish →", "Рассказать →", "Tell me →"),
    ("shell.ai_assistant", "AI yordamchi", "AI-помощник", "AI assistant"),
    ("shell.ai_header_alt", "Replix AI yordamchi", "AI-помощник Replix", "Replix AI assistant"),
    ("shell.ai_placeholder", "Savolingizni yozing...", "Напишите ваш вопрос...", "Type your question..."),
    ("shell.send", "Yuborish", "Отправить", "Send"),
    ("shell.ai_greeting",
     "Salom! 👋 Men sizning AI yordamchingizman -- qolgan barcha narsada yordam bera olaman: lidlar, xarajat, natijalar, target holati haqida real ma'lumot beraman. Nima kerakligini yozing, masalan: \"bugun necha lead keldi\", \"CPL qancha\" yoki \"eng yaxshi target qaysi\".",
     "Привет! 👋 Я ваш AI-помощник — помогу во всём остальном: дам реальные данные о лидах, расходах, результатах и состоянии таргета. Напишите, что нужно, например: «сколько лидов пришло сегодня», «какой CPL» или «какой таргет лучший».",
     "Hi! 👋 I'm your AI assistant — I can help with everything else: real data on leads, spend, results and how your ads are doing. Just tell me what you need, e.g. \"how many leads came in today\", \"what's the CPL\" or \"which campaign is best\"."),
    ("shell.ai_typing", "Yozyapti...", "Печатает...", "Typing..."),
    ("shell.ai_error_reply", "Kechirasiz, javob olishda xatolik yuz berdi.", "Извините, не удалось получить ответ.", "Sorry, something went wrong while getting a reply."),
    ("shell.ai_error_network", "⚠️ Serverga ulanishda xatolik yuz berdi. Qayta urinib ko'ring.", "⚠️ Ошибка подключения к серверу. Попробуйте ещё раз.", "⚠️ Could not reach the server. Please try again."),

    # ---- dashboard.html ----
    ("dashboard.title", "Dashboard", "Дашборд", "Dashboard"),
    ("dashboard.subtitle", "Butun kompaniya bo'yicha umumiy ko'rinish", "Общая картина по всей компании", "Company-wide overview"),
    ("dashboard.updated_at", "Yangilangan {time} UTC", "Обновлено {time} UTC", "Updated {time} UTC"),
    ("dashboard.btn_target", "Target (reklama)", "Таргет (реклама)", "Ads"),
    ("dashboard.btn_analytics", "Batafsil Analitika", "Подробная аналитика", "Detailed analytics"),
    ("dashboard.followup_reminder", "Qayta aloqa eslatmasi:", "Напоминание о повторном контакте:", "Follow-up reminder:"),
    ("dashboard.overdue_n", "{n} ta muddati o'tgan", "{n} просрочено", "{n} overdue"),
    ("dashboard.today_n", "{n} ta bugun", "{n} на сегодня", "{n} today"),
    ("dashboard.view_all", "Barchasini ko'rish", "Смотреть все", "View all"),
    ("dashboard.kpi_total_leads", "Jami lidlar", "Всего лидов", "Total leads"),
    ("dashboard.kpi_new_leads", "{period} yangi lidlar", "{period}: новые лиды", "New leads ({period})"),
    ("dashboard.kpi_sales", "{period} sotuvlar", "{period}: продажи", "Sales ({period})"),
    ("dashboard.kpi_turnover", "{period} oborot", "{period}: оборот", "Revenue ({period})"),
    ("dashboard.kpi_conversion", "Konversiya (sotildi)", "Конверсия (продано)", "Conversion (sold)"),
    ("dashboard.kpi_bonus_month", "Shu oy jami bonus", "Бонусы за этот месяц", "Total bonus this month"),
    ("dashboard.kpi_progress_title", "Menejerlar KPI progressi", "Прогресс KPI менеджеров", "Manager KPI progress"),
    ("dashboard.kpi_progress_note", "(shu oy · keyingi bosqichgacha qancha qoldi)", "(этот месяц · сколько осталось до следующей ступени)", "(this month · how far to the next tier)"),
    ("dashboard.th_manager", "Menejer", "Менеджер", "Manager"),
    ("dashboard.th_sales_month", "Shu oy sotuv", "Продаж за месяц", "Sales this month"),
    ("dashboard.th_sales_to_next", "Keyingi bosqichgacha sotuv", "Продаж до следующей ступени", "Sales to next tier"),
    ("dashboard.th_current_salary", "Hozirgi oylik (oklad+bonus)", "Текущая зарплата (оклад+бонус)", "Current pay (base+bonus)"),
    ("dashboard.th_next_tier_salary", "Keyingi bosqichda (sotuv soni oshsa)", "На следующей ступени (если продаж станет больше)", "At next tier (with more sales)"),
    ("dashboard.th_to_next_milestone", "Keyingi oborot pog'onasigacha", "До следующего порога оборота", "To next revenue milestone"),
    ("dashboard.th_milestone_salary", "Shu pog'onada oylik", "Зарплата на этом пороге", "Pay at that milestone"),
    ("dashboard.n_pcs", "{n} ta", "{n}", "{n}"),
    ("dashboard.top_tier", "eng yuqori bosqichda", "на высшей ступени", "at the top tier"),
    ("dashboard.up_to", "({amount}gacha)", "(до {amount})", "(up to {amount})"),
    ("dashboard.empty_managers", "Hali faol menejer yoki sotuv yo'q.", "Пока нет активных менеджеров или продаж.", "No active managers or sales yet."),
    ("dashboard.lead_status", "Lidlar holati", "Статусы лидов", "Lead status"),
    ("dashboard.empty_leads", "Hali lidlar yo'q.", "Лидов пока нет.", "No leads yet."),
    ("dashboard.leaderboard", "Menejerlar reytingi", "Рейтинг менеджеров", "Manager leaderboard"),
    ("dashboard.leaderboard_note", "(shu oy, oborot bo'yicha)", "(этот месяц, по обороту)", "(this month, by revenue)"),
    ("dashboard.sales_trend", "Sotuvlar dinamikasi", "Динамика продаж", "Sales trend"),
    ("dashboard.sales_trend_note", "(shu oy, kunlik oborot)", "(этот месяц, оборот по дням)", "(this month, daily revenue)"),
    ("dashboard.empty_sales_month", "Bu oyda hali sotuv qayd etilmagan.", "В этом месяце продаж пока не зафиксировано.", "No sales recorded this month yet."),
    ("dashboard.calls_title", "Jamoa gaplashuv faolligi", "Активность звонков команды", "Team call activity"),
    ("dashboard.calls_note", "(shu oy, kuniga {n} kishi -- jamoa rejasi)", "(этот месяц, {n} чел. в день — план команды)", "(this month, {n} people/day — team target)"),
    ("dashboard.calls_not_configured",
     "Moi Zvonki hali ulanmagan -- jamoa gaplashuv faolligi diagrammasi ko'rinishi uchun API sozlanishi kerak (Render environment variables).",
     "Moi Zvonki ещё не подключён — чтобы увидеть диаграмму активности звонков, нужно настроить API (переменные окружения Render).",
     "Moi Zvonki is not connected yet — configure the API (Render environment variables) to see the team call activity chart."),
    ("dashboard.overview_title", "Target / SMM / Instagram — to'liq ko'rinish", "Таргет / SMM / Instagram — полная картина", "Ads / SMM / Instagram — full overview"),
    ("dashboard.overview_note", "(so'nggi 30 kun)", "(последние 30 дней)", "(last 30 days)"),
    ("dashboard.target_card", "Target (Meta reklama)", "Таргет (реклама Meta)", "Ads (Meta)"),
    ("dashboard.details", "Batafsil →", "Подробнее →", "Details →"),
    ("dashboard.spend", "Xarajat", "Расход", "Spend"),
    ("dashboard.leads_crm", "Lidlar (CRM)", "Лиды (CRM)", "Leads (CRM)"),
    ("dashboard.sold", "Sotildi", "Продано", "Sold"),
    ("dashboard.active_campaigns", "Faol kampaniya", "Активных кампаний", "Active campaigns"),
    ("dashboard.meta_not_connected", "Hali Meta (Facebook/Instagram) hisobingiz ulanmagan.", "Аккаунт Meta (Facebook/Instagram) ещё не подключён.", "Your Meta (Facebook/Instagram) account is not connected yet."),
    ("dashboard.connect_account", "Akkauntni ulash", "Подключить аккаунт", "Connect account"),
    ("dashboard.ask_admin", "Ulash uchun administratorga murojaat qiling.", "Для подключения обратитесь к администратору.", "Ask your administrator to connect it."),
    ("dashboard.followers", "Obunachilar", "Подписчики", "Followers"),
    ("dashboard.growth_month", "Bu oy o'sish", "Рост за месяц", "Growth this month"),
    ("dashboard.total_engagement", "Jami faollik", "Вовлечённость", "Total engagement"),
    ("dashboard.engagement_rate", "Engagement rate", "Engagement rate", "Engagement rate"),
    ("dashboard.dm_title", "Instagram xabarlar (DM)", "Сообщения Instagram (DM)", "Instagram messages (DM)"),
    ("dashboard.dm_total", "Jami suhbatlar", "Всего диалогов", "Total conversations"),
    ("dashboard.dm_unanswered", "Javobsiz", "Без ответа", "Unanswered"),
    ("dashboard.dm_hot", "\"Issiq\" lidlar", "«Горячие» лиды", "\"Hot\" leads"),
    ("dashboard.dm_new_today", "Bugun yangi xabar", "Новых сообщений сегодня", "New messages today"),
    ("dashboard.chart_turnover", "Oborot", "Оборот", "Revenue"),
    ("dashboard.chart_daily_turnover", "Kunlik oborot", "Оборот за день", "Daily revenue"),
    ("dashboard.chart_real_calls", "Haqiqiy gaplashuvlar", "Фактические разговоры", "Actual calls"),
    ("dashboard.chart_team_plan", "Jamoa rejasi", "План команды", "Team target"),

    # ---- leads.html ----
    ("leads.title", "Lidlar", "Лиды", "Leads"),
    ("leads.subtitle", "Meta Lead Ads'dan avtomatik tortilgan + qo'lda qo'shilgan/import qilingan lidlar", "Лиды, автоматически полученные из Meta Lead Ads + добавленные вручную/импортированные", "Leads pulled automatically from Meta Lead Ads + added manually/imported"),
    ("leads.excel_import", "Excel import", "Импорт из Excel", "Excel import"),
    ("leads.new_lead", "+ Yangi lead", "+ Новый лид", "+ New lead"),
    ("leads.usage_over",
     "CRM'da <strong>{used} / {limit}</strong> lid ishlatilgan -- joriy tarifingiz limitidan oshdingiz. Yangi lidlar hamon qabul qilinadi, lekin ko'proq joy uchun tarifni yangilashni tavsiya qilamiz.",
     "В CRM использовано <strong>{used} / {limit}</strong> лидов — вы превысили лимит текущего тарифа. Новые лиды по-прежнему принимаются, но для большего объёма рекомендуем повысить тариф.",
     "You've used <strong>{used} / {limit}</strong> leads in your CRM — you're over your current plan's limit. New leads are still accepted, but we recommend upgrading for more room."),
    ("leads.usage_near",
     "CRM'da <strong>{used} / {limit}</strong> lid ishlatilgan ({percent}%) -- tez orada tarifingiz limitiga yetasiz.",
     "В CRM использовано <strong>{used} / {limit}</strong> лидов ({percent}%) — скоро вы достигнете лимита тарифа.",
     "You've used <strong>{used} / {limit}</strong> leads in your CRM ({percent}%) — you'll reach your plan's limit soon."),
    ("leads.upgrade_plan", "Tarifni yangilash →", "Повысить тариф →", "Upgrade plan →"),
    ("leads.viewing_company",
     "<strong>{name}</strong> kompaniyasining lidlari ko'rsatilyapti (platforma egasi rejimi).",
     "Показаны лиды компании <strong>{name}</strong> (режим владельца платформы).",
     "Showing leads for <strong>{name}</strong> (platform owner mode)."),
    ("leads.back_to_companies", "← Kompaniyalarga qaytish", "← К компаниям", "← Back to companies"),
    ("leads.incomplete_notice",
     "⚠️ <strong>{n}</strong> ta lidda ism yoki telefon raqami yo'q (chala to'ldirilgan) -- menejerlar ularni to'ldirishi kerak.",
     "⚠️ У <strong>{n}</strong> лидов нет имени или телефона (заполнены не полностью) — менеджерам нужно их дополнить.",
     "⚠️ <strong>{n}</strong> leads are missing a name or phone number (incomplete) — managers should fill them in."),
    ("leads.incomplete_download", "Excel ro'yxatini yuklab olish ↓", "Скачать список в Excel ↓", "Download Excel list ↓"),
    ("leads.search_placeholder", "Ism, telefon yoki kampaniya bo'yicha qidirish...", "Поиск по имени, телефону или кампании...", "Search by name, phone or campaign..."),
    ("leads.only_group", "Faqat <strong>{group}</strong> lidlar ko'rsatilyapti.", "Показаны только <strong>{group}</strong> лиды.", "Showing only <strong>{group}</strong> leads."),
    ("leads.group_new", "yangi (hali bog'lanilmagan)", "новые (ещё без контакта)", "new (not contacted yet)"),
    ("leads.group_processed", "ishlangan (bog'lanilgan/sifatli/sifatsiz/sotilgan)", "обработанные (контакт/качественный/некачественный/продан)", "processed (contacted/qualified/unqualified/sold)"),
    ("leads.remove_filter", "Olib tashlash", "Убрать", "Remove"),
    ("leads.filter", "Filtr", "Фильтр", "Filter"),
    ("leads.source", "Manba", "Источник", "Source"),
    ("leads.form", "Forma", "Форма", "Form"),
    ("leads.target_campaign", "Target (kampaniya)", "Таргет (кампания)", "Campaign"),
    ("leads.apply", "Qo'llash", "Применить", "Apply"),
    ("leads.clear", "Tozalash", "Сбросить", "Clear"),
    ("leads.th_name", "Ism", "Имя", "Name"),
    ("leads.th_phone", "Telefon", "Телефон", "Phone"),
    ("leads.th_target", "Target (kampaniya / adset / reklama)", "Таргет (кампания / адсет / объявление)", "Campaign / ad set / ad"),
    ("leads.th_form", "Forma", "Форма", "Form"),
    ("leads.th_source", "Manba", "Источник", "Source"),
    ("leads.th_status", "Holat", "Статус", "Status"),
    ("leads.th_manager", "Menejer", "Менеджер", "Manager"),
    ("leads.th_date", "Sana", "Дата", "Date"),
    ("leads.extra_phone_title", "Qo'shimcha telefon: {phone}", "Дополнительный телефон: {phone}", "Additional phone: {phone}"),
    ("leads.empty", "Hali lead yo'q.", "Лидов пока нет.", "No leads yet."),
    ("leads.pagination", "Jami {total} ta lead · {page}/{pages}-sahifa", "Всего {total} лидов · страница {page}/{pages}", "{total} leads total · page {page}/{pages}"),
    ("leads.prev", "← Oldingi", "← Назад", "← Previous"),
    ("leads.next", "Keyingi →", "Далее →", "Next →"),

    # ---- lead_detail.html ----
    ("lead_detail.title_fallback", "Lead", "Лид", "Lead"),
    ("lead_detail.back", "← Lidlar ro'yxatiga qaytish", "← К списку лидов", "← Back to leads"),
    ("lead_detail.no_name", "Ism ko'rsatilmagan", "Имя не указано", "No name given"),
    ("lead_detail.source_label", "manba:", "источник:", "source:"),
    ("lead_detail.source_meta", "Meta (avtomatik)", "Meta (автоматически)", "Meta (automatic)"),
    ("lead_detail.source_manual", "Qo'lda qo'shilgan", "Добавлен вручную", "Added manually"),
    ("lead_detail.source_import", "Excel import", "Импорт из Excel", "Excel import"),
    ("lead_detail.confirm_delete", "Bu leadni o'chirishni tasdiqlaysizmi?", "Удалить этого лида?", "Delete this lead?"),
    ("lead_detail.info", "Ma'lumot", "Информация", "Details"),
    ("lead_detail.phone", "Telefon", "Телефон", "Phone"),
    ("lead_detail.phone2", "Qo'shimcha telefon", "Дополнительный телефон", "Additional phone"),
    ("lead_detail.campaign", "Kampaniya", "Кампания", "Campaign"),
    ("lead_detail.adset", "Adset", "Адсет", "Ad set"),
    ("lead_detail.ad", "Reklama / video", "Объявление / видео", "Ad / video"),
    ("lead_detail.status", "Holat", "Статус", "Status"),
    ("lead_detail.manager", "Mas'ul menejer", "Ответственный менеджер", "Assigned manager"),
    ("lead_detail.total_sales", "Jami sotuv summasi", "Общая сумма продаж", "Total sales amount"),
    ("lead_detail.followup", "Qayta aloqa", "Повторный контакт", "Follow-up"),
    ("lead_detail.days_overdue", "{n} kun kechikdi", "просрочено на {n} дн.", "{n} days overdue"),
    ("lead_detail.today", "bugun", "сегодня", "today"),
    ("lead_detail.in_days", "{n} kundan keyin", "через {n} дн.", "in {n} days"),
    ("lead_detail.other_answers", "Formaning boshqa javoblari", "Другие ответы из формы", "Other form answers"),
    ("lead_detail.other_answers_note", "Ism/telefon/email'dan tashqari, Instant Form'dagi qolgan savollarga berilgan javoblar.", "Ответы на остальные вопросы Instant Form, кроме имени/телефона/email.", "Answers to the remaining Instant Form questions, apart from name/phone/email."),
    ("lead_detail.sales", "Sotuvlar", "Продажи", "Sales"),
    ("lead_detail.sales_note", "Shu mijozning har bir alohida xaridi -- 1-sotuv, 2-sotuv va h.k. KPI/bonus hisobi shu ro'yxatdan olinadi.", "Каждая отдельная покупка этого клиента — 1-я, 2-я продажа и т.д. KPI/бонусы считаются по этому списку.", "Each separate purchase by this customer — 1st sale, 2nd sale, etc. KPI/bonus calculations are based on this list."),
    ("lead_detail.sale_n", "{n}-sotuv", "{n}-я продажа", "Sale #{n}"),
    ("lead_detail.invoice_no", "· nakladnoy №{n}", "· накладная №{n}", "· invoice #{n}"),
    ("lead_detail.returned", "qaytarilgan", "возврат", "returned"),
    ("lead_detail.confirm_return",
     "Bu sotuvni QAYTARILGAN deb belgilaysizmi? KPI/bonus hisobidan chiqarib tashlanadi, lekin yozuv tarixda saqlanadi.",
     "Отметить эту продажу как ВОЗВРАТ? Она будет исключена из расчёта KPI/бонусов, но запись останется в истории.",
     "Mark this sale as RETURNED? It will be excluded from KPI/bonus calculations, but the record stays in the history."),
    ("lead_detail.mark_returned", "Qaytarilgan deb belgilash", "Отметить как возврат", "Mark as returned"),
    ("lead_detail.confirm_delete_sale",
     "Bu sotuvni BEKOR QILASIZMI? Yozuv bazadan BUTUNLAY o'chib ketadi, tarixda ham qolmaydi -- bu qaytarib bo'lmaydigan amal (faqat xato kiritilgan sotuvlar uchun ishlating).",
     "ОТМЕНИТЬ эту продажу? Запись будет ПОЛНОСТЬЮ удалена из базы и не останется в истории — это необратимое действие (используйте только для ошибочно введённых продаж).",
     "CANCEL this sale? The record will be PERMANENTLY deleted from the database and won't remain in the history — this cannot be undone (use only for sales entered by mistake)."),
    ("lead_detail.cancel_sale", "Bekor qilish", "Отменить", "Cancel"),
    ("lead_detail.no_sales", "Hali sotuv qo'shilmagan.", "Продаж пока нет.", "No sales added yet."),
    ("lead_detail.new_sale_amount", "Yangi sotuv summasi (so'm)", "Сумма новой продажи (сум)", "New sale amount (UZS)"),
    ("lead_detail.amount_placeholder", "masalan 750000", "например 750000", "e.g. 750000"),
    ("lead_detail.invoice_label", "Nakladnoy № (ixtiyoriy)", "Накладная № (необязательно)", "Invoice # (optional)"),
    ("lead_detail.invoice_placeholder", "masalan 00123", "например 00123", "e.g. 00123"),
    ("lead_detail.add_sale", "Sotuv qo'shish", "Добавить продажу", "Add sale"),
    ("lead_detail.history", "Tarix", "История", "History"),
    ("lead_detail.no_notes", "Hali izoh yo'q.", "Комментариев пока нет.", "No notes yet."),
    ("lead_detail.edit_title", "Ma'lumot va holatni tahrirlash", "Редактировать данные и статус", "Edit details and status"),
    ("lead_detail.qualification", "Kvalifikatsiya", "Квалификация", "Qualification"),
    ("lead_detail.qualification_note", "Qo'ng'iroq qilib mijoz bilan gaplashgandan keyin shu yerni to'ldiring", "Заполните после звонка и разговора с клиентом", "Fill this in after calling and talking to the customer"),
    ("lead_detail.not_selected", "— tanlanmagan —", "— не выбрано —", "— not selected —"),
    ("lead_detail.full_name", "To'liq ism", "Полное имя", "Full name"),
    ("lead_detail.full_name_placeholder", "Ism Familiya", "Имя Фамилия", "First Last"),
    ("lead_detail.phone2_optional", "Qo'shimcha telefon (ixtiyoriy)", "Дополнительный телефон (необязательно)", "Additional phone (optional)"),
    ("lead_detail.status_note",
     "Sotuv summasini kiritish uchun yuqoridagi \"Sotuvlar\" bo'limidan foydalaning -- holatni \"Sotildi\"ga o'zgartirish shu yerda, sotuv summasi alohida qo'shiladi.",
     "Чтобы указать сумму продажи, используйте раздел «Продажи» выше — здесь меняется только статус на «Продано», сумма добавляется отдельно.",
     "To enter a sale amount, use the \"Sales\" section above — here you only change the status to \"Sold\"; the amount is added separately."),
    ("lead_detail.note_optional", "Izoh (ixtiyoriy)", "Комментарий (необязательно)", "Note (optional)"),
    ("lead_detail.note_placeholder", "Masalan: qo'ng'iroq qilindi, narx aytildi...", "Например: позвонили, озвучили цену...", "e.g. called, quoted the price..."),
    ("lead_detail.followup_note",
     "Mijoz bilan gaplashib bo'lgach, keyingi safar qachon bog'lanish kerakligini shu yerda belgilang -- o'sha kun kelganda \"Qayta aloqa\" bo'limida va Telegram orqali eslatiladi.",
     "После разговора с клиентом укажите здесь, когда связаться в следующий раз — в этот день напомним в разделе «Повторный контакт» и через Telegram.",
     "After talking to the customer, set when to get back in touch — on that day you'll be reminded in the \"Follow-ups\" section and via Telegram."),
    ("lead_detail.followup_date", "Qayta aloqa sanasi", "Дата повторного контакта", "Follow-up date"),
    ("lead_detail.followup_date_note", "Bo'sh qoldirib saqlasangiz, qayta aloqa bekor qilinadi.", "Если оставить пустым и сохранить, повторный контакт будет отменён.", "Leave empty and save to cancel the follow-up."),
    ("lead_detail.followup_about", "Nima haqida (ixtiyoriy)", "О чём (необязательно)", "About what (optional)"),
    ("lead_detail.followup_about_placeholder", "Masalan: narx bo'yicha o'ylab ko'rmoqchi, oyoxirida qayta qo'ng'iroq qilish kerak", "Например: думает над ценой, перезвонить в конце месяца", "e.g. thinking about the price, call back at the end of the month"),

    # ---- lead_new.html ----
    ("lead_new.title", "Yangi lead", "Новый лид", "New lead"),
    ("lead_new.h1", "Yangi lead qo'shish", "Добавить нового лида", "Add a new lead"),
    ("lead_new.subtitle", "Qo'lda kelgan (qo'ng'iroq, DM, do'kon va h.k.) leadni bu yerdan qo'shing", "Добавьте лида, пришедшего вручную (звонок, DM, магазин и т.д.)", "Add a lead that came in manually (call, DM, walk-in, etc.)"),
    ("lead_new.full_name", "Ism familiya", "Имя и фамилия", "Full name"),
    ("lead_new.phone", "Telefon", "Телефон", "Phone"),
    ("lead_new.phone2", "Qo'shimcha telefon (ixtiyoriy)", "Дополнительный телефон (необязательно)", "Additional phone (optional)"),
    ("lead_new.email", "Email (ixtiyoriy)", "Email (необязательно)", "Email (optional)"),
    ("lead_new.campaign", "Kampaniya nomi (ixtiyoriy)", "Название кампании (необязательно)", "Campaign name (optional)"),
    ("lead_new.adset", "Adset nomi (ixtiyoriy)", "Название адсета (необязательно)", "Ad set name (optional)"),
    ("lead_new.ad", "Reklama / video nomi (ixtiyoriy)", "Название объявления / видео (необязательно)", "Ad / video name (optional)"),

    # ---- leads_import.html ----
    ("leads_import.title", "Excel import", "Импорт из Excel", "Excel import"),
    ("leads_import.h1", "Excel/CSV'dan lead import qilish", "Импорт лидов из Excel/CSV", "Import leads from Excel/CSV"),
    ("leads_import.subtitle", "Meta'dan eksport qilingan yoki boshqa manbadagi lead faylini yuklang (.xlsx yoki .csv)", "Загрузите файл с лидами, экспортированный из Meta или из другого источника (.xlsx или .csv)", "Upload a lead file exported from Meta or another source (.xlsx or .csv)"),
    ("leads_import.file", "Fayl", "Файл", "File"),
    ("leads_import.help",
     "Birinchi qator sarlavha bo'lishi kerak. Tanib olinadigan ustun nomlari: <code>full_name</code>/<code>ism</code>, <code>phone</code>/<code>telefon</code>, <code>email</code>, <code>campaign_name</code>/<code>kampaniya</code>. Telefon raqami bo'yicha dublikatlar avtomatik o'tkazib yuboriladi.",
     "Первая строка должна быть заголовком. Распознаваемые названия столбцов: <code>full_name</code>/<code>ism</code>, <code>phone</code>/<code>telefon</code>, <code>email</code>, <code>campaign_name</code>/<code>kampaniya</code>. Дубликаты по номеру телефона пропускаются автоматически.",
     "The first row must be a header. Recognised column names: <code>full_name</code>/<code>ism</code>, <code>phone</code>/<code>telefon</code>, <code>email</code>, <code>campaign_name</code>/<code>kampaniya</code>. Duplicates by phone number are skipped automatically."),
    ("leads_import.submit", "Import qilish", "Импортировать", "Import"),

    # ---- companies.html ----
    ("companies.title", "Kompaniyalar", "Компании", "Companies"),
    ("companies.subtitle", "Multi-tenant asosi -- har bir mijoz-kompaniyaning tarif/to'lov holati. Faqat platforma egasi ko'radi.", "Основа multi-tenant — тариф и статус оплаты каждой компании-клиента. Видно только владельцу платформы.", "Multi-tenant base — each client company's plan and payment status. Visible to the platform owner only."),
    ("companies.site_submissions", "Sayt murojaatlari", "Заявки с сайта", "Website enquiries"),
    ("companies.ai_conversations", "AI-suhbatlar", "AI-диалоги", "AI conversations"),
    ("companies.new_company", "Yangi kompaniya", "Новая компания", "New company"),
    ("companies.new_company_title", "Yangi kompaniya qo'shish", "Добавить новую компанию", "Add a new company"),
    ("companies.new_note_prefix", "Mijozlar endi", "Клиенты теперь могут зарегистрироваться сами через", "Customers can now sign up themselves via"),
    ("companies.new_note_suffix",
     "orqali o'zlari ham ro'yxatdan o'ta oladi -- bu forma faqat SIZ qo'lda (masalan telefon/uchrashuvda kelishilgan mijoz uchun) kompaniya ochib berish uchun. Yangi kompaniya 5 kunlik sinov muddati bilan, va DARHOL o'ziga tegishli admin hisobi bilan boshlanadi.",
     "— эта форма нужна только когда ВЫ вручную открываете компанию (например, для клиента, с которым договорились по телефону/на встрече). Новая компания начинает с 5-дневного пробного периода и СРАЗУ получает собственный аккаунт администратора.",
     "— this form is only for when YOU open a company manually (e.g. for a customer agreed by phone/in a meeting). A new company starts with a 5-day trial and IMMEDIATELY gets its own admin account."),
    ("companies.name", "Kompaniya nomi", "Название компании", "Company name"),
    ("companies.email_optional", "Email (ixtiyoriy)", "Email (необязательно)", "Email (optional)"),
    ("companies.email_placeholder", "mijoz@misol.uz", "client@example.uz", "client@example.uz"),
    ("companies.plan", "Tarif", "Тариф", "Plan"),
    ("companies.plan_trial", "Sinov (trial)", "Пробный (trial)", "Trial"),
    ("companies.plan_start", "Boshlang'ich", "Начальный", "Starter"),
    ("companies.plan_business", "Biznes", "Бизнес", "Business"),
    ("companies.plan_unlimited", "Cheklovsiz", "Безлимит", "Unlimited"),
    ("companies.th_name", "Nomi", "Название", "Name"),
    ("companies.th_source", "Manba", "Источник", "Source"),
    ("companies.th_admin", "Admin login", "Логин админа", "Admin login"),
    ("companies.th_plan", "Tarif", "Тариф", "Plan"),
    ("companies.th_managers", "Menejerlar", "Менеджеры", "Managers"),
    ("companies.th_paid_until", "To'lov muddati", "Оплачено до", "Paid until"),
    ("companies.th_status", "Holat", "Статус", "Status"),
    ("companies.th_created", "Qo'shilgan", "Добавлена", "Created"),
    ("companies.badge_you", "siz", "вы", "you"),
    ("companies.badge_new", "yangi", "новая", "new"),
    ("companies.source_self", "o'zi ro'yxatdan o'tgan", "самостоятельная регистрация", "self-signup"),
    ("companies.source_admin", "admin qo'shgan", "добавлена админом", "added by admin"),
    ("companies.unlimited", "cheklovsiz", "без ограничений", "unlimited"),
    ("companies.status_suspended", "to'xtatilgan", "приостановлена", "suspended"),
    ("companies.status_active", "faol", "активна", "active"),
    ("companies.status_expired", "to'lov tugagan", "оплата истекла", "payment expired"),
    ("companies.crm_view", "CRM ko'rish", "Смотреть CRM", "View CRM"),
    ("companies.view", "Ko'rish", "Смотреть", "View"),
    ("companies.confirm_suspend",
     "Rostdan ham '{name}' to'xtatilsinmi? Bu kompaniyaning hamma foydalanuvchisi tizimga kira olmay qoladi.",
     "Точно приостановить «{name}»? Все пользователи этой компании потеряют доступ к системе.",
     "Really suspend '{name}'? All users of this company will lose access to the system."),
    ("companies.suspend", "To'xtatish", "Приостановить", "Suspend"),
    ("companies.activate", "Yoqish", "Включить", "Activate"),
    ("companies.empty", "Hali kompaniya yo'q.", "Компаний пока нет.", "No companies yet."),
    ("companies.delete_title", "Kompaniyani o'chirish", "Удалить компанию", "Delete company"),
    ("companies.delete_warning",
     "<strong>\"<span id=\"companyDeleteName\"></span>\"</strong> kompaniyasi va unga tegishli BARCHA ma'lumot (menejerlar, leadlar, qo'ng'iroqlar, SMM, Instagram xabarlari, sozlamalar) <strong class=\"text-bad\">butunlay va qaytarib bo'lmaydigan tarzda</strong> o'chiriladi. Faqat kirishni to'xtatmoqchi bo'lsangiz, buning o'rniga \"To'xtatish\"ni ishlating.",
     "Компания <strong>«<span id=\"companyDeleteName\"></span>»</strong> и ВСЕ её данные (менеджеры, лиды, звонки, SMM, сообщения Instagram, настройки) будут удалены <strong class=\"text-bad\">полностью и безвозвратно</strong>. Если хотите лишь закрыть доступ, используйте «Приостановить».",
     "The company <strong>\"<span id=\"companyDeleteName\"></span>\"</strong> and ALL of its data (managers, leads, calls, SMM, Instagram messages, settings) will be deleted <strong class=\"text-bad\">completely and irreversibly</strong>. If you only want to block access, use \"Suspend\" instead."),
    ("companies.delete_confirm_label", "Tasdiqlash uchun kompaniya nomini aynan shunday yozing:", "Для подтверждения введите название компании точно так:", "To confirm, type the company name exactly:"),
    ("companies.delete_forever", "Butunlay o'chirish", "Удалить навсегда", "Delete permanently"),
    ("companies.crm_view_note", "Kerak bo'lsa, faqat ma'lum forma(lar)dan kelgan va/yoki yangi/ishlangan lidlarni tanlab ko'rsatishingiz mumkin. Hech narsa belgilamasangiz, hammasi ko'rsatiladi.", "При необходимости можно показать только лидов из определённых форм и/или новых/обработанных. Если ничего не выбрать, будут показаны все.", "If needed, show only leads from specific form(s) and/or new/processed ones. Leave everything unselected to show all."),
    ("companies.status", "Holat", "Статус", "Status"),
    ("companies.group_new", "Yangi (hali bog'lanilmagan)", "Новые (ещё без контакта)", "New (not contacted yet)"),
    ("companies.group_processed", "Ishlangan (bog'lanilgan/sifatli/sifatsiz/sotilgan)", "Обработанные (контакт/качественный/некачественный/продан)", "Processed (contacted/qualified/unqualified/sold)"),
    ("companies.forms", "Forma(lar)", "Форма(ы)", "Form(s)"),
    ("companies.loading", "Yuklanmoqda...", "Загрузка...", "Loading..."),
    ("companies.go_crm", "CRM'ga o'tish", "Перейти в CRM", "Go to CRM"),
    ("companies.no_forms", "Bu kompaniyada hali Instant Formadan kelgan lead yo'q.", "У этой компании пока нет лидов из Instant Form.", "This company has no leads from Instant Forms yet."),
    ("companies.forms_error", "Formalarni yuklab bo'lmadi.", "Не удалось загрузить формы.", "Could not load forms."),

    # ---- company_edit.html ----
    ("company_edit.title_suffix", "Kompaniya", "Компания", "Company"),
    ("company_edit.status", "Holat:", "Статус:", "Status:"),
    ("company_edit.manage_managers", "Bu kompaniyaning menejerlarini boshqarish", "Управлять менеджерами этой компании", "Manage this company's managers"),
    ("company_edit.quick_actions", "Tezkor amallar", "Быстрые действия", "Quick actions"),
    ("company_edit.quick_note", "To'lov Payme/Click orqali qo'lda tekshirilib, shu yerda belgilanadi (avtomatik integratsiya hali yo'q).", "Оплата проверяется вручную через Payme/Click и отмечается здесь (автоматической интеграции пока нет).", "Payments are checked manually via Payme/Click and recorded here (no automatic integration yet)."),
    ("company_edit.extend_30", "+ 30 kunga uzaytirish (to'lov keldi)", "+ Продлить на 30 дней (оплата получена)", "+ Extend by 30 days (payment received)"),
    ("company_edit.remove_limit", "Muddat cheklovini olib tashlash (cheksiz)", "Снять ограничение по сроку (бессрочно)", "Remove the time limit (unlimited)"),
    ("company_edit.confirm_suspend", "Rostdan ham to'xtatilsinmi? Bu kompaniyaning HAMMA foydalanuvchisi CRM'ga kira olmay qoladi.", "Точно приостановить? ВСЕ пользователи этой компании потеряют доступ к CRM.", "Really suspend? ALL users of this company will lose access to the CRM."),
    ("company_edit.suspend", "Hisobni to'xtatish", "Приостановить аккаунт", "Suspend account"),
    ("company_edit.details", "Tafsilotlar", "Детали", "Details"),
    ("company_edit.name", "Nomi", "Название", "Name"),
    ("company_edit.plan", "Tarif", "Тариф", "Plan"),
    ("company_edit.free", "bepul", "бесплатно", "free"),
    ("company_edit.per_month", "/oy", "/мес", "/mo"),
    ("company_edit.unlimited", "(cheklovsiz)", "(без ограничений)", "(unlimited)"),
    ("company_edit.paid_until", "To'lov muddati (bo'sh -- cheklovsiz)", "Оплачено до (пусто — без ограничений)", "Paid until (empty — unlimited)"),
    ("company_edit.active", "Hisob faol", "Аккаунт активен", "Account active"),
    ("company_edit.back", "← Kompaniyalar ro'yxatiga qaytish", "← К списку компаний", "← Back to companies"),

    # ---- managers.html / manager_edit.html ----
    ("managers.title", "Menejerlar", "Менеджеры", "Managers"),
    ("managers.back_company", "← Kompaniyaga qaytish", "← К компании", "← Back to company"),
    ("managers.subtitle_owner", "Platforma egasi sifatida shu kompaniyaning menejerlarini boshqaryapsiz.", "Вы управляете менеджерами этой компании как владелец платформы.", "You are managing this company's managers as the platform owner."),
    ("managers.subtitle", "Faqat admin yangi menejer/admin hisob qo'sha oladi", "Только админ может добавлять новых менеджеров/админов", "Only an admin can add new manager/admin accounts"),
    ("managers.new_account", "Yangi hisob", "Новый аккаунт", "New account"),
    ("managers.new_account_title", "Yangi hisob qo'shish", "Добавить новый аккаунт", "Add a new account"),
    ("managers.username", "Username", "Логин", "Username"),
    ("managers.full_name", "To'liq ism", "Полное имя", "Full name"),
    ("managers.password", "Parol", "Пароль", "Password"),
    ("managers.phone_optional", "Telefon raqami (ixtiyoriy)", "Номер телефона (необязательно)", "Phone number (optional)"),
    ("managers.moizvonki", "Moi Zvonki login/email (ixtiyoriy) — qo'ng'iroqlarni shu menejerga bog'lash uchun", "Логин/email Moi Zvonki (необязательно) — чтобы привязать звонки к этому менеджеру", "Moi Zvonki login/email (optional) — to link calls to this manager"),
    ("managers.moizvonki_placeholder", "menejer@pochta.uz", "manager@mail.uz", "manager@mail.uz"),
    ("managers.telegram_id", "Telegram ID (ixtiyoriy) — qayta aloqa eslatmasi shaxsan shu yerga yuboriladi", "Telegram ID (необязательно) — напоминания о повторном контакте будут приходить лично сюда", "Telegram ID (optional) — follow-up reminders are sent here personally"),
    ("managers.telegram_placeholder", "masalan 123456789", "например 123456789", "e.g. 123456789"),
    ("managers.hire_date", "Ish boshlagan sana (ixtiyoriy, KPI rejasini oy o'rtasidan proratsiya qilish uchun)", "Дата начала работы (необязательно, для пропорционального расчёта плана KPI с середины месяца)", "Start date (optional, to prorate the KPI plan from mid-month)"),
    ("managers.role", "Rol", "Роль", "Role"),
    ("managers.role_manager", "Menejer", "Менеджер", "Manager"),
    ("managers.role_admin", "Admin", "Админ", "Admin"),
    ("managers.modules", "Dostup berilgan bo'limlar (menejer uchun; admin uchun har doim hammasi ochiq)", "Доступные разделы (для менеджера; админу всегда открыто всё)", "Accessible sections (for managers; admins always have full access)"),
    ("managers.th_username", "Username", "Логин", "Username"),
    ("managers.th_name", "Ism", "Имя", "Name"),
    ("managers.th_role", "Rol", "Роль", "Role"),
    ("managers.th_phone", "Telefon", "Телефон", "Phone"),
    ("managers.th_moizvonki", "Moi Zvonki login", "Логин Moi Zvonki", "Moi Zvonki login"),
    ("managers.th_telegram", "Telegram ID", "Telegram ID", "Telegram ID"),
    ("managers.th_hired", "Ish boshlagan", "Начал работу", "Started"),
    ("managers.th_active", "Faol", "Активен", "Active"),
    ("managers.active", "faol", "активен", "active"),
    ("managers.inactive", "nofaol", "неактивен", "inactive"),
    ("manager_edit.title", "Tahrirlash", "Редактирование", "Edit"),
    ("manager_edit.back", "← Menejerlar ro'yxatiga qaytish", "← К списку менеджеров", "← Back to managers"),
    ("manager_edit.subtitle", "Username, ism, rol, faollik va parolni shu yerdan o'zgartirish mumkin", "Здесь можно изменить логин, имя, роль, активность и пароль", "Change the username, name, role, status and password here"),
    ("manager_edit.new_password", "Yangi parol (ixtiyoriy — bo'sh qoldirsangiz o'zgarmaydi)", "Новый пароль (необязательно — если оставить пустым, не изменится)", "New password (optional — leave empty to keep the current one)"),
    ("manager_edit.new_password_placeholder", "Yangi parol", "Новый пароль", "New password"),
    ("manager_edit.active", "Faol hisob", "Аккаунт активен", "Active account"),

    # ---- manager_daily_activity.html ----
    ("manager_activity.title", "Menejer faoliyati", "Активность менеджеров", "Manager activity"),
    ("manager_activity.subtitle", "Har bir menejer tanlangan kun ichida nechta lead bilan ishlagani va nechtasini kvalifikatsiya qilgani.", "Сколько лидов каждый менеджер обработал за выбранный день и сколько квалифицировал.", "How many leads each manager worked on the selected day and how many they qualified."),
    ("manager_activity.th_manager", "Menejer", "Менеджер", "Manager"),
    ("manager_activity.th_contacted", "Gaplashgan lidlar", "Лидов в работе", "Leads contacted"),
    ("manager_activity.th_qualified", "Sifatli qilingan", "Квалифицированы", "Qualified"),
    ("manager_activity.th_unqualified", "Sifatsiz qilingan", "Некачественные", "Unqualified"),
    ("manager_activity.th_sold", "Sotilgan", "Продано", "Sold"),
    ("manager_activity.th_events", "Jami harakat", "Всего действий", "Total actions"),
    ("manager_activity.empty", "Bu kunda hech qanday lead bilan ishlanmagan.", "В этот день ни один лид не обрабатывался.", "No leads were worked on this day."),
    ("manager_activity.footnote",
     "\"Gaplashgan lidlar\" -- shu kun ichida kamida bir marta statusi/izohi saqlangan ALOHIDA lidlar soni (bitta lead bir necha marta saqlansa ham bir marta hisoblanadi). \"Jami harakat\" -- barcha saqlashlar soni (takrorlar bilan).",
     "«Лидов в работе» — число УНИКАЛЬНЫХ лидов, у которых за день хотя бы раз сохранён статус/комментарий (один лид, сохранённый несколько раз, считается один раз). «Всего действий» — число всех сохранений (с повторами).",
     "\"Leads contacted\" — the number of DISTINCT leads whose status/note was saved at least once that day (a lead saved several times counts once). \"Total actions\" — the number of all saves (including repeats)."),

    # ---- my_profile.html ----
    ("profile.title", "Mening profilim", "Мой профиль", "My profile"),
    ("profile.role_admin", "Administrator", "Администратор", "Administrator"),
    ("profile.role_manager", "Menejer", "Менеджер", "Manager"),
    ("profile.telegram_title", "Telegram ulanishim", "Моё подключение Telegram", "My Telegram connection"),
    ("profile.telegram_note",
     "Bitta tugma bilan ulaysiz -- hech qanday ID qo'lda kiritilmaydi. Shaxsiy chatga faqat sizga tegishli narsalar keladi (qayta aloqa eslatmalari, lidlar bo'yicha savollar) -- umumiy xarajat/byudjet hisobotlari bu yerga kelmaydi.",
     "Подключается одной кнопкой — никаких ID вводить вручную не нужно. В личный чат приходит только то, что касается вас (напоминания о повторном контакте, вопросы по лидам) — общие отчёты по расходам/бюджету сюда не приходят.",
     "Connect with a single button — no IDs to type by hand. Your personal chat only receives what concerns you (follow-up reminders, questions about leads) — company-wide spend/budget reports don't come here."),
    ("profile.personal_telegram", "Shaxsiy Telegram", "Личный Telegram", "Personal Telegram"),
    ("profile.connected", "✅ Ulangan", "✅ Подключено", "✅ Connected"),
    ("profile.not_connected", "Ulanmagan", "Не подключено", "Not connected"),
    ("profile.reconnect", "Qayta ulash", "Переподключить", "Reconnect"),
    ("profile.connect_one_click", "Bitta tugma bilan ulash", "Подключить одной кнопкой", "Connect with one click"),
    ("profile.tasks_group", "Vazifalar guruhi", "Группа задач", "Tasks group"),
    ("profile.tasks_group_note", "Kompaniyadagi barcha xodim uchun UMUMIY -- bitta marta ulash yetarli", "ОБЩАЯ для всех сотрудников компании — достаточно подключить один раз", "SHARED by everyone in the company — connecting once is enough"),
    ("profile.connect_other_group", "Boshqa guruh ulash", "Подключить другую группу", "Connect another group"),
    ("profile.connect_group", "Guruhni ulash", "Подключить группу", "Connect group"),
    ("profile.group_howto", "Guruhni ulash uchun: tugmani bosing → Telegram guruh tanlash oynasini ko'rsatadi → guruhni tanlang.", "Чтобы подключить группу: нажмите кнопку → Telegram покажет окно выбора группы → выберите группу.", "To connect a group: press the button → Telegram shows a group picker → choose the group."),

    # ---- followups.html ----
    ("followups.title", "Qayta aloqa", "Повторный контакт", "Follow-ups"),
    ("followups.subtitle", "{scope} rejalashtirilgan qayta aloqalar -- eng shoshilinchi (kechikkan/bugungi) tepada", "Запланированные повторные контакты {scope} — самые срочные (просроченные/сегодняшние) сверху", "Scheduled follow-ups {scope} — most urgent (overdue/today) first"),
    ("followups.scope_all", "Barcha menejerlar bo'yicha", "по всем менеджерам", "across all managers"),
    ("followups.scope_mine", "Sizga biriktirilgan lidlar bo'yicha", "по закреплённым за вами лидам", "for leads assigned to you"),
    ("followups.overdue", "Muddati o'tgan", "Просрочено", "Overdue"),
    ("followups.total_planned", "Jami rejalashtirilgan", "Всего запланировано", "Total scheduled"),
    ("followups.th_status", "Holat", "Статус", "Status"),
    ("followups.th_name", "Ism", "Имя", "Name"),
    ("followups.th_phone", "Telefon", "Телефон", "Phone"),
    ("followups.th_manager", "Menejer", "Менеджер", "Manager"),
    ("followups.th_lead_status", "Lead holati", "Статус лида", "Lead status"),
    ("followups.th_date", "Qayta aloqa sanasi", "Дата повторного контакта", "Follow-up date"),
    ("followups.th_note", "Izoh", "Комментарий", "Note"),
    ("followups.unknown", "Noma'lum", "Неизвестно", "Unknown"),
    ("followups.empty", "Hali qayta aloqa rejalashtirilmagan -- lead sahifasida \"Qayta aloqa\" bo'limidan sana belgilang.", "Повторные контакты пока не запланированы — укажите дату в разделе «Повторный контакт» на странице лида.", "No follow-ups scheduled yet — set a date in the \"Follow-up\" section on a lead's page."),

    # ---- sold_customers.html ----
    ("sold.title", "Sotilgan xaridorlar", "Покупатели", "Sold customers"),
    ("sold.subtitle", "Har bir xarid alohida qator -- bitta mijoz bir necha marta xarid qilgan bo'lsa, har biri alohida ko'rinadi.", "Каждая покупка — отдельная строка: если клиент покупал несколько раз, каждая покупка показана отдельно.", "Each purchase is a separate row — if a customer bought several times, each purchase is shown separately."),
    ("sold.purchases_count", "Xaridlar soni", "Число покупок", "Purchases"),
    ("sold.total_amount", "Jami summa", "Общая сумма", "Total amount"),
    ("sold.search_placeholder", "Ism yoki telefon bo'yicha qidirish...", "Поиск по имени или телефону...", "Search by name or phone..."),
    ("sold.first_purchase", "1-xarid", "1-я покупка", "1st purchase"),
    ("sold.repeat_purchase", "Takroriy xarid (2+)", "Повторная покупка (2+)", "Repeat purchase (2+)"),
    ("sold.th_customer", "Xaridor", "Покупатель", "Customer"),
    ("sold.th_phone", "Telefon", "Телефон", "Phone"),
    ("sold.th_manager", "Menejer", "Менеджер", "Manager"),
    ("sold.th_purchase_no", "Xarid raqami", "Номер покупки", "Purchase #"),
    ("sold.th_amount", "Summa", "Сумма", "Amount"),
    ("sold.th_invoice", "Chek/Nakladnoy", "Чек/Накладная", "Receipt/Invoice"),
    ("sold.th_date", "Sana", "Дата", "Date"),
    ("sold.nth_purchase", "{n}-xarid (takroriy)", "{n}-я покупка (повторная)", "Purchase #{n} (repeat)"),
    ("sold.view", "ko'rish", "смотреть", "view"),
    ("sold.empty", "Bu filtr bo'yicha xarid topilmadi.", "По этому фильтру покупок не найдено.", "No purchases match this filter."),

    # ---- _trial_nudge.html ----
    ("trial_nudge.message_aria", "Xabar", "Сообщение", "Message"),
    ("trial_nudge.dialog_aria", "Bepul sinov taklifi", "Предложение бесплатного пробного периода", "Free trial offer"),
    ("trial_nudge.assistant", "AI yordamchi", "AI-помощник", "AI assistant"),
    ("trial_nudge.text",
     "👋 Hali sinab ko'rmadingizmi? Instagram/Facebook natijalaringizni <strong>5 kun bepul</strong> ko'ring — karta ma'lumoti shart emas.",
     "👋 Ещё не пробовали? Посмотрите результаты вашей рекламы в Instagram/Facebook <strong>5 дней бесплатно</strong> — карта не нужна.",
     "👋 Haven't tried it yet? See your Instagram/Facebook results <strong>free for 5 days</strong> — no card details required."),
    ("trial_nudge.cta", "5 kun bepul boshlash", "Начать бесплатно на 5 дней", "Start 5 days free"),
]

for _key, _uz, _ru, _en in _APP_STRINGS:
    TRANSLATIONS["uz"][_key] = _uz
    TRANSLATIONS["ru"][_key] = _ru
    TRANSLATIONS["en"][_key] = _en
del _key, _uz, _ru, _en


def translate(key: str, lang: str, **kwargs) -> str:
    table = TRANSLATIONS.get(lang) or TRANSLATIONS[DEFAULT_LANG]
    val = table.get(key)
    if val is None:
        # Yetishmagan kalit -- avtomatik standart tilga (o'zbekcha) qaytadi,
        # HECH QACHON xato bermaydi yoki kalitning o'zini ko'rsatmaydi.
        val = TRANSLATIONS[DEFAULT_LANG].get(key, key)
    if kwargs:
        # Dinamik qism ("{n} ta lid"). Placeholder yetishmasa/noto'g'ri
        # bo'lsa ham sahifa buzilmaydi -- xom matn qaytadi.
        try:
            return val.format(**kwargs)
        except (KeyError, IndexError, ValueError, AttributeError):
            return val
    return val
